export type StoreCategory =
  | "showrooms"
  | "boutiques"
  | "fast_fashion"
  | "individual_fashion"
  | "flour_mill"
  | "palamuthir"
  | "meat_fish"
  | "pharmacy"
  | "stationery"
  | "home_decor"
  | "kitchen_appliances"
  | "fashion_accessories"
  | "bakery"
  | "grocery"
  | "restaurants"
  | "supermarkets"
  | "sweet_shops"
  | "cafes"
  | "fruits_veg"
  | "fashion"
  | "footwear"
  | "jewellery"
  | "electronics"
  | "mobile"
  | "books_stationery"
  | "beauty"
  | "home_kitchen"
  | "furniture"
  | "hardware"
  | "sports"
  | "toys"
  | "gifts"
  | "flowers"
  | "pet_shops"
  | "pooja"
  | "auto"
  | "repair"
  | "local_services";

export interface Store {
  id: string;
  name: string;
  category: StoreCategory;
  tagline: string;
  distanceKm: number;
  rating: number;
  isOpen: boolean;
  etaMin: number;
  address: string;
  lat: number;
  lng: number;
  imageUrl: string;
}

export interface DeliveryCategory {
  id: string;
  label: string;
  imageUrl: string;
  filter?: StoreCategory;
}

const catImg = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=300&q=75`;
const storeImg = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=75`;
const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=300&q=75`;

export const APPROVED_STORE: Store = {
  id: "approved-catalog",
  name: "Verified local products",
  category: "palamuthir",
  tagline: "Approved by Seller Hub",
  distanceKm: 2,
  rating: 5,
  isOpen: true,
  etaMin: 30,
  address: "Available from approved local vendors",
  lat: 11.0028,
  lng: 77.0865,
  imageUrl: catImg("photo-1542838132-92c53300491e"),
};

export const deliveryCategories: DeliveryCategory[] = [
  {
    id: "palamuthir",
    label: "Palamuthir Nilayam (பழமுதிர்)",
    imageUrl: catImg("photo-1610832958506-aa56368176cf"),
    filter: "palamuthir",
  },
  {
    id: "flour_mill",
    label: "Flour Mill (மாவு ஆலை)",
    imageUrl: catImg("photo-1586201375761-83865001e31c"),
    filter: "flour_mill",
  },
  {
    id: "meat_fish",
    label: "Meat, Fish & Chicken",
    imageUrl: catImg("photo-1607623814075-e51df1bdc82f"),
    filter: "meat_fish",
  },
  {
    id: "fashion_accessories",
    label: "Chain, Kammal & Gifts",
    imageUrl: catImg("photo-1535632066927-ab7c9ab60908"),
    filter: "fashion_accessories",
  },
  {
    id: "boutiques",
    label: "Designer Boutiques",
    imageUrl: catImg("photo-1558769132-cb1aea458c5e"),
    filter: "boutiques",
  },
  {
    id: "fast_fashion",
    label: "Fast Fashion (Branded)",
    imageUrl: catImg("photo-1489987707025-afc232f7ea0f"),
    filter: "fast_fashion",
  },
  {
    id: "showrooms",
    label: "Showrooms",
    imageUrl: catImg("photo-1555529669-e69e7aa0ba9a"),
    filter: "showrooms",
  },
  {
    id: "kitchen_appliances",
    label: "Kitchen Appliances (பாத்திரம்)",
    imageUrl: catImg("photo-1556911220-e15b29be8c8f"),
    filter: "kitchen_appliances",
  },
  {
    id: "home_decor",
    label: "Interior & Home Decor",
    imageUrl: catImg("photo-1513519245088-0e12902e5a38"),
    filter: "home_decor",
  },
  {
    id: "individual_fashion",
    label: "Individual Fashion",
    imageUrl: catImg("photo-1441986300917-64674bd600d8"),
    filter: "individual_fashion",
  },
  {
    id: "pharmacy",
    label: "Individual Pharmacy",
    imageUrl: catImg("photo-1587854692152-cbe660dbde88"),
    filter: "pharmacy",
  },
  {
    id: "stationery",
    label: "Book Stall & Stationery",
    imageUrl: catImg("photo-1519682337058-a94d519337bc"),
    filter: "stationery",
  },
];

export interface Product {
  id: string;
  storeId: string;
  name: string;
  unit: string;
  price: number;
  category: string;
  imageUrl?: string;
  stock?: number;
}

export const categoryColor: Partial<Record<StoreCategory, string>> = {
  showrooms: "#4F46E5",
  boutiques: "#DB2777",
  fast_fashion: "#7C3AED",
  individual_fashion: "#E11D48",
  flour_mill: "#D97706",
  palamuthir: "#16A34A",
  meat_fish: "#DC2626",
  pharmacy: "#0284C7",
  stationery: "#CA8A04",
  home_decor: "#059669",
  kitchen_appliances: "#475569",
  fashion_accessories: "#EC4899",
  bakery: "#B36A3E",
  grocery: "#059669",
  restaurants: "#E11D48",
};

export const categoryLabel: Partial<Record<StoreCategory, string>> = {
  showrooms: "Showrooms",
  boutiques: "Designer Boutiques",
  fast_fashion: "Fast Fashion (Branded)",
  individual_fashion: "Individual Fashion",
  flour_mill: "Flour & Masala Mill (மாவு & மசாலா ஆலை)",
  palamuthir: "Palamuthir Nilayam (பழமுதிர்)",
  meat_fish: "Meat, Fish & Chicken",
  pharmacy: "Individual Pharmacy",
  stationery: "Book Stalls & Stationery",
  home_decor: "Interior & Home Decor",
  kitchen_appliances: "Kitchen Appliances",
  fashion_accessories: "Fashion Accessories & Gifts",
  bakery: "Bakery",
  grocery: "Kirana & Grocery",
  restaurants: "Restaurants",
};

const legacyStores: Store[] = [
  {
    id: "s_roja_bakes",
    name: "Roja Bakes & Sweets (பாப்பம்பட்டி பிரிவு)",
    category: "bakery",
    tagline: "Oven fresh bread, Roja special Mysurpa, Roti, Puffs & Sweets",
    distanceKm: 0.4,
    rating: 4.9,
    isOpen: true,
    etaMin: 15,
    address: "Main Road, Pappampatti Pirivu, Coimbatore",
    lat: 10.999,
    lng: 76.974,
    imageUrl: storeImg("photo-1509440159596-0249088772ff"),
  },
  {
    id: "s_roja_mart",
    name: "Roja Supermarket & Kirana",
    category: "grocery",
    tagline: "Daily fresh groceries, Roja atta, snacks & household essentials",
    distanceKm: 0.6,
    rating: 4.8,
    isOpen: true,
    etaMin: 18,
    address: "Pappampatti Pirivu Bus Stop, Coimbatore",
    lat: 10.9985,
    lng: 76.973,
    imageUrl: storeImg("photo-1604719312566-8912e9227c6a"),
  },
  // ── 0. Swiggy Featured Restaurants & Bakes ──────────────────────────────────────
  {
    id: "s_haribhavanam",
    name: "Haribhavanam",
    category: "meat_fish",
    tagline: "Authentic South Indian Non-Veg, Meals, Biryani & Chettinad Specials",
    distanceKm: 0.8,
    rating: 4.9,
    isOpen: true,
    etaMin: 20,
    address: "Trichy Road, Sungam Junction, Coimbatore",
    lat: 10.9995,
    lng: 76.9745,
    imageUrl: storeImg("photo-1555396273-367ea4eb4db5"),
  },
  {
    id: "s_terminal2",
    name: "Terminal 2 (Unit of Haribhavanam)",
    category: "meat_fish",
    tagline: "Gourmet Burgers, Harissa Wraps, Kebabs & Continental Delights",
    distanceKm: 1.2,
    rating: 4.8,
    isOpen: true,
    etaMin: 22,
    address: "Race Course Road, Coimbatore",
    lat: 10.998,
    lng: 76.971,
    imageUrl: storeImg("photo-1568901346375-23c9450c58cd"),
  },
  // ── 1. Fresh Stalls & Bakes ────────────────────────────────────────────────────────────
  {
    id: "s_paap1",
    name: "Sri Krishna Sweets & Bakery (பாப்பம்பட்டி பிரிவு)",
    category: "bakery",
    tagline: "Fresh Mysurpa, hot savouries, tea, puffs & daily bakery items",
    distanceKm: 0.3,
    rating: 4.9,
    isOpen: true,
    etaMin: 15,
    address: "Pappampatti Pirivu Junction, Trichy Road, Coimbatore",
    lat: 11.0028,
    lng: 77.0865,
    imageUrl: storeImg("photo-1586201375761-83865001e31c"),
  },
  {
    id: "s_kiran1",
    name: "Anand Kirana Provision Store",
    category: "flour_mill",
    tagline: "Fresh batter, pulses, coconut oil & daily kitchen ration",
    distanceKm: 0.4,
    rating: 4.7,
    isOpen: true,
    etaMin: 18,
    address: "12, Trichy Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0027,
    lng: 77.086,
    imageUrl: storeImg("photo-1604719312566-8912e9227c6a"),
  },
  {
    id: "s_groc2",
    name: "Singanallur Super Groceries & Rice Mart",
    category: "flour_mill",
    tagline: "Bulk Sona Masoori rice, organic pulses, cold pressed oil & spices",
    distanceKm: 3.3,
    rating: 4.8,
    isOpen: true,
    etaMin: 28,
    address: "Trichy Road, Singanallur Junction, Coimbatore",
    lat: 10.9982,
    lng: 77.0255,
    imageUrl: storeImg("photo-1578916171728-46686eac8d58"),
  },
  {
    id: "s_groc3",
    name: "Ondipudur Daily Fresh Supermarket",
    category: "palamuthir",
    tagline: "Complete family fresh produce, fruits & dairy items",
    distanceKm: 5.5,
    rating: 4.7,
    isOpen: true,
    etaMin: 35,
    address: "Main Road, Ondipudur Hub, Coimbatore",
    lat: 10.9925,
    lng: 77.0528,
    imageUrl: storeImg("photo-1542838132-92c53300491e"),
  },

  // ── 2. Palamuthir ─────────────────────────────────────────────────────────
  {
    id: "s_paap2",
    name: "Pappampatti Organic Super Mart & Fruits (பழமுதிர்)",
    category: "palamuthir",
    tagline: "Daily fresh organic fruits, tender coconut, hill banana & farm veggies",
    distanceKm: 0.5,
    rating: 4.8,
    isOpen: true,
    etaMin: 18,
    address: "Opp. IOC Fuel Station, Pappampatti Pirivu, Coimbatore",
    lat: 11.0035,
    lng: 77.0872,
    imageUrl: storeImg("photo-1610832958506-aa56368176cf"),
  },
  {
    id: "s_pala1",
    name: "Kovai Pazhamudir Nilayam (பழமுதிர்)",
    category: "palamuthir",
    tagline: "Daily fresh organic fruits, tender coconut & veggies",
    distanceKm: 0.7,
    rating: 4.8,
    isOpen: true,
    etaMin: 20,
    address: "88, Trichy Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0038,
    lng: 77.0875,
    imageUrl: storeImg("photo-1610832958506-aa56368176cf"),
  },
  {
    id: "s_pala2",
    name: "Green Coast Organic Fruit & Veggie Bazaar",
    category: "palamuthir",
    tagline: "Organic mangoes, pomegranate, fresh greens & tender coconut",
    distanceKm: 1.2,
    rating: 4.9,
    isOpen: true,
    etaMin: 22,
    address: "55, Garden Avenue, Pappampatti Pirivu, Coimbatore",
    lat: 11.0055,
    lng: 77.0869,
    imageUrl: storeImg("photo-1610832958506-aa56368176cf"),
  },
  {
    id: "s_pala3",
    name: "Singanallur Fresh Farm Palamuthir",
    category: "palamuthir",
    tagline: "Farm fresh vegetables, apples, avocados & hydroponic greens",
    distanceKm: 3.6,
    rating: 4.7,
    isOpen: true,
    etaMin: 30,
    address: "Kamraj Road, Singanallur Junction, Coimbatore",
    lat: 10.9978,
    lng: 77.0262,
    imageUrl: storeImg("photo-1540420773420-3366772f4999"),
  },

  // ── 3. Flour Mill ─────────────────────────────────────────────────────────
  {
    id: "s_paap3",
    name: "Sri Selvamani Flour & Masala Mill (பாப்பம்பட்டி மாவு ஆலை)",
    category: "flour_mill",
    tagline: "Fresh Idli/Dosa batter, milled wheat & freshly ground sambar masala",
    distanceKm: 0.4,
    rating: 4.9,
    isOpen: true,
    etaMin: 16,
    address: "Selvapuram Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0019,
    lng: 77.0858,
    imageUrl: storeImg("photo-1586201375761-83865001e31c"),
  },
  {
    id: "s_flour1",
    name: "Sri Lakshmi Flour & Masala Mill (மாவு & மசாலா ஆலை)",
    category: "flour_mill",
    tagline: "Fresh Idli/Dosa batter, milled wheat & freshly ground individual masalas",
    distanceKm: 0.5,
    rating: 4.9,
    isOpen: true,
    etaMin: 18,
    address: "14, Temple Car Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0025,
    lng: 77.0862,
    imageUrl: storeImg("photo-1586201375761-83865001e31c"),
  },
  {
    id: "s_flour2",
    name: "Amman Maavu Mill & Pure Spices",
    category: "flour_mill",
    tagline: "Pure Ground Rice flour, Chilly & Sambar powder",
    distanceKm: 1.7,
    rating: 4.7,
    isOpen: true,
    etaMin: 28,
    address: "51, South Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0018,
    lng: 77.0848,
    imageUrl: storeImg("photo-1615485290382-441e4d049cb5"),
  },
  {
    id: "s_flour3",
    name: "Sri Murugan Batter & Masala Mill",
    category: "flour_mill",
    tagline: "Daily milled Idli batter, Ragi flour & homemade podi",
    distanceKm: 0.8,
    rating: 4.8,
    isOpen: true,
    etaMin: 20,
    address: "12, Bazaar Lane, Pappampatti Pirivu, Coimbatore",
    lat: 11.0026,
    lng: 77.0859,
    imageUrl: storeImg("photo-1586201375761-83865001e31c"),
  },
  {
    id: "s_flour4",
    name: "Ondipudur Heritage Flour & Spice Mill",
    category: "flour_mill",
    tagline: "Traditional stone milled spices, multi-grain flour & fresh batter",
    distanceKm: 6.0,
    rating: 4.9,
    isOpen: true,
    etaMin: 38,
    address: "Bazaar Road, Ondipudur Hub, Coimbatore",
    lat: 10.9918,
    lng: 77.0535,
    imageUrl: storeImg("photo-1615485290382-441e4d049cb5"),
  },

  // ── 4. Meat, Fish & Chicken ───────────────────────────────────────────────
  {
    id: "s_paap4",
    name: "Kongu Country Mutton & Farm Chicken Stall",
    category: "meat_fish",
    tagline: "Fresh tender Mutton, Nattu Kozhi (Country Chicken) & farm eggs",
    distanceKm: 0.6,
    rating: 4.8,
    isOpen: true,
    etaMin: 20,
    address: "Kamaraj Nagar, Pappampatti Pirivu, Coimbatore",
    lat: 11.0041,
    lng: 77.0849,
    imageUrl: storeImg("photo-1607623814075-e51df1bdc82f"),
  },
  {
    id: "s_meat1",
    name: "Annachi Mutton & Farm Chicken Stall",
    category: "meat_fish",
    tagline: "Tender Mutton, Country Chicken & Farm Eggs",
    distanceKm: 0.9,
    rating: 4.8,
    isOpen: true,
    etaMin: 22,
    address: "42, Market Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0045,
    lng: 77.0852,
    imageUrl: storeImg("photo-1607623814075-e51df1bdc82f"),
  },
  {
    id: "s_fish1",
    name: "Kadalkani Fresh Fish & Seafood Stall",
    category: "meat_fish",
    tagline: "Daily fresh Vanjaram slices, Mathi, Nethili & Prawns",
    distanceKm: 1.5,
    rating: 4.8,
    isOpen: true,
    etaMin: 24,
    address: "Daily Market Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0048,
    lng: 77.0839,
    imageUrl: storeImg("photo-1534422298391-e4f8c172dddb"),
  },
  {
    id: "s_meat2",
    name: "Ondipudur Fresh Sea Fish & Mutton Stall",
    category: "meat_fish",
    tagline: "Freshly caught sea fish, crab, prawns & soft mutton curry cuts",
    distanceKm: 6.4,
    rating: 4.9,
    isOpen: true,
    etaMin: 40,
    address: "Market Corner, Ondipudur Hub, Coimbatore",
    lat: 10.9912,
    lng: 77.0515,
    imageUrl: storeImg("photo-1534422298391-e4f8c172dddb"),
  },

  // ── 5. Pharmacy ───────────────────────────────────────────────────────────
  {
    id: "s_paap5",
    name: "Sri Lakshmi Medicals & Healthcare",
    category: "pharmacy",
    tagline: "24/7 chemist, surgicals, OTC medicines & baby care",
    distanceKm: 0.2,
    rating: 4.7,
    isOpen: true,
    etaMin: 12,
    address: "Pappampatti Pirivu Bus Stop, Trichy Road, Coimbatore",
    lat: 11.0022,
    lng: 77.0878,
    imageUrl: storeImg("photo-1587854692152-cbe660dbde88"),
  },
  {
    id: "s_pharm1",
    name: "Sri Ram Medicals & Chemist",
    category: "pharmacy",
    tagline: "24/7 individual chemist, OTC medicines & surgicals",
    distanceKm: 0.8,
    rating: 4.6,
    isOpen: true,
    etaMin: 20,
    address: "Corner of 5th Cross, Pappampatti Pirivu, Coimbatore",
    lat: 11.0029,
    lng: 77.0871,
    imageUrl: storeImg("photo-1587854692152-cbe660dbde88"),
  },
  {
    id: "s_pharm2",
    name: "Apollo Pharmacy Franchise",
    category: "pharmacy",
    tagline: "Branded medicines, health supplements & digital diagnostics",
    distanceKm: 3.4,
    rating: 4.8,
    isOpen: true,
    etaMin: 25,
    address: "Trichy Main Road, Singanallur Junction, Coimbatore",
    lat: 10.9985,
    lng: 77.0248,
    imageUrl: storeImg("photo-1576602976047-174e57a47881"),
  },
  {
    id: "s_pharm3",
    name: "Care Wellness Chemist & Healthcare",
    category: "pharmacy",
    tagline: "Ayurvedic remedies, orthopedic supports & 24/7 emergency drugs",
    distanceKm: 5.7,
    rating: 4.7,
    isOpen: true,
    etaMin: 36,
    address: "Station Road, Ondipudur Hub, Coimbatore",
    lat: 10.9928,
    lng: 77.0542,
    imageUrl: storeImg("photo-1587854692152-cbe660dbde88"),
  },

  // ── 6. Individual Fashion ─────────────────────────────────────────────────
  {
    id: "s_paap6",
    name: "Pappampatti Readymades & Menswear",
    category: "individual_fashion",
    tagline: "Quality cotton shirts, dhotis, pants & casual wear",
    distanceKm: 0.7,
    rating: 4.6,
    isOpen: true,
    etaMin: 22,
    address: "Near SBI ATM, Pappampatti Pirivu, Coimbatore",
    lat: 11.0031,
    lng: 77.086,
    imageUrl: storeImg("photo-1441986300917-64674bd600d8"),
  },
  {
    id: "s_fash1",
    name: "Kumaran Readymades & Menswear",
    category: "individual_fashion",
    tagline: "Individual shop for cotton shirts, pants, dhotis & tailoring",
    distanceKm: 1.1,
    rating: 4.5,
    isOpen: true,
    etaMin: 25,
    address: "29, North Car Street, Pappampatti, Coimbatore",
    lat: 11.0012,
    lng: 77.0855,
    imageUrl: storeImg("photo-1441986300917-64674bd600d8"),
  },
  {
    id: "s_fash2",
    name: "Kovai Cotton Dhotis & Menswear",
    category: "individual_fashion",
    tagline: "Pure Ramraj cotton dhotis, linen shirts & ethnic wear",
    distanceKm: 4.3,
    rating: 4.8,
    isOpen: true,
    etaMin: 32,
    address: "Commercial Hub, Singanallur Junction, Coimbatore",
    lat: 10.9975,
    lng: 77.027,
    imageUrl: storeImg("photo-1617137984095-74e4e5e3613f"),
  },
  {
    id: "s_fash3",
    name: "Nila Kids & Family Readymades",
    category: "individual_fashion",
    tagline: "Kids party wear, cotton frock sets & men's formals",
    distanceKm: 5.9,
    rating: 4.7,
    isOpen: true,
    etaMin: 37,
    address: "Main Market, Ondipudur Hub, Coimbatore",
    lat: 10.993,
    lng: 77.051,
    imageUrl: storeImg("photo-1441986300917-64674bd600d8"),
  },

  // ── 7. Boutiques ──────────────────────────────────────────────────────────
  {
    id: "s_bout1",
    name: "Ananya Designer Boutique",
    category: "boutiques",
    tagline: "Handloom Silk Sarees, Designer Kurtis & Bridal Tailoring",
    distanceKm: 1.2,
    rating: 4.9,
    isOpen: true,
    etaMin: 25,
    address: "18, Heritage Avenue, Trichy Road, Coimbatore",
    lat: 11.0051,
    lng: 77.0882,
    imageUrl: storeImg("photo-1558769132-cb1aea458c5e"),
  },
  {
    id: "s_bout2",
    name: "Vogue Handloom Silk Boutique",
    category: "boutiques",
    tagline: "Kanchipuram Silk Sarees, Designer Blouses & Embroidery",
    distanceKm: 0.9,
    rating: 4.8,
    isOpen: true,
    etaMin: 24,
    address: "77, Heritage Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0036,
    lng: 77.0879,
    imageUrl: storeImg("photo-1583391733956-6c78276477e2"),
  },
  {
    id: "s_bout3",
    name: "Sri Lakshmi Bridal & Embroidery Studio",
    category: "boutiques",
    tagline: "Custom Aari work blouses, bridal lehengas & silk saree stitching",
    distanceKm: 4.1,
    rating: 4.7,
    isOpen: true,
    etaMin: 30,
    address: "Near Temple Arch, Singanallur Junction, Coimbatore",
    lat: 10.9968,
    lng: 77.0258,
    imageUrl: storeImg("photo-1537633552985-df8429e8048b"),
  },
  {
    id: "s_bout4",
    name: "Silk & Threads Custom Boutique",
    category: "boutiques",
    tagline: "Handmade designer kurtis, ethnic dupattas & party gowns",
    distanceKm: 5.8,
    rating: 4.8,
    isOpen: true,
    etaMin: 36,
    address: "Park View, Ondipudur Hub, Coimbatore",
    lat: 10.9922,
    lng: 77.0538,
    imageUrl: storeImg("photo-1558769132-cb1aea458c5e"),
  },

  // ── 8. Showrooms ──────────────────────────────────────────────────────────
  {
    id: "s_show1",
    name: "Sri Saravana Textiles & Electronics Showroom",
    category: "showrooms",
    tagline: "Multistory showroom for silk, smart TVs & appliances",
    distanceKm: 1.4,
    rating: 4.7,
    isOpen: true,
    etaMin: 28,
    address: "100 Feet Commercial Road, Singanallur - Pappampatti stretch, Coimbatore",
    lat: 11.0062,
    lng: 77.0835,
    imageUrl: storeImg("photo-1555529669-e69e7aa0ba9a"),
  },
  {
    id: "s_show2",
    name: "Premier Electronics & Appliances Showroom",
    category: "showrooms",
    tagline: "LG, Samsung 4K TVs, double door fridges & washing machines",
    distanceKm: 3.8,
    rating: 4.8,
    isOpen: true,
    etaMin: 32,
    address: "Trichy Main Road, Singanallur Junction, Coimbatore",
    lat: 10.9988,
    lng: 77.0242,
    imageUrl: storeImg("photo-1593784991095-a205069470b6"),
  },
  {
    id: "s_show3",
    name: "Royal Silk & Diamond Showroom",
    category: "showrooms",
    tagline: "3-Floor wedding silk sarees, gold jewellery & diamond showroom",
    distanceKm: 6.2,
    rating: 4.9,
    isOpen: true,
    etaMin: 40,
    address: "Grand Highway, Ondipudur Hub, Coimbatore",
    lat: 10.9915,
    lng: 77.0522,
    imageUrl: storeImg("photo-1610030469983-98e550d6193c"),
  },

  // ── 9. Fast Fashion ───────────────────────────────────────────────────────
  {
    id: "s_fast1",
    name: "Trendz & Zudio Fast Fashion Outlet",
    category: "fast_fashion",
    tagline: "Branded youth apparel, casuals, denims & footwear",
    distanceKm: 1.6,
    rating: 4.6,
    isOpen: true,
    etaMin: 30,
    address: "Plaza Complex, Ondipudur-Pappampatti Road, Coimbatore",
    lat: 11.0021,
    lng: 77.0891,
    imageUrl: storeImg("photo-1489987707025-afc232f7ea0f"),
  },
  {
    id: "s_fast2",
    name: "Urban Style Youth Apparel",
    category: "fast_fashion",
    tagline: "Graphic tees, cargo trousers, hoodies & casual western tops",
    distanceKm: 3.5,
    rating: 4.7,
    isOpen: true,
    etaMin: 28,
    address: "Express Mall Road, Singanallur Junction, Coimbatore",
    lat: 10.9972,
    lng: 77.0265,
    imageUrl: storeImg("photo-1541099649105-f69ad21f3246"),
  },
  {
    id: "s_fast3",
    name: "Maxx Fashion Store",
    category: "fast_fashion",
    tagline: "Trendy women western wear, denim jackets & kids casuals",
    distanceKm: 6.5,
    rating: 4.8,
    isOpen: true,
    etaMin: 42,
    address: "Shopping Arcade, Ondipudur Hub, Coimbatore",
    lat: 10.9908,
    lng: 77.0545,
    imageUrl: storeImg("photo-1489987707025-afc232f7ea0f"),
  },

  // ── 10. Kitchen Appliances ────────────────────────────────────────────────
  {
    id: "s_kitch1",
    name: "Murugan Stainless Steel & Pressure Cooker House",
    category: "kitchen_appliances",
    tagline: "Stainless steel utensils, mixer grinders & pressure cookers",
    distanceKm: 1.3,
    rating: 4.7,
    isOpen: true,
    etaMin: 26,
    address: "63, Vessels Bazaar Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0032,
    lng: 77.0841,
    imageUrl: storeImg("photo-1556909114-f6e7ad7d3136"),
  },
  {
    id: "s_kitch2",
    name: "Sri Ganesh Kitchen Mixer & Vessels World",
    category: "kitchen_appliances",
    tagline: "Preethi grinders, Hawkins cookers & non-stick cookware",
    distanceKm: 3.9,
    rating: 4.8,
    isOpen: true,
    etaMin: 32,
    address: "Bus Stand Road, Singanallur Junction, Coimbatore",
    lat: 10.9981,
    lng: 77.0238,
    imageUrl: storeImg("photo-1584269600464-37b1b58a9fe7"),
  },
  {
    id: "s_kitch3",
    name: "Kovai Chef Utensils & Stove Clinic",
    category: "kitchen_appliances",
    tagline: "Gas stoves, chimney hoods, cast iron kadai & brassware",
    distanceKm: 6.7,
    rating: 4.6,
    isOpen: true,
    etaMin: 45,
    address: "Bazaar Street, Ondipudur Hub, Coimbatore",
    lat: 10.9902,
    lng: 77.0518,
    imageUrl: storeImg("photo-1556909114-f6e7ad7d3136"),
  },

  // ── 11. Home Decor ────────────────────────────────────────────────────────
  {
    id: "s_decor1",
    name: "Vasantham Interior Home Decor Studio",
    category: "home_decor",
    tagline: "Wallpapers, curtains, brass Agal lamps & wall art",
    distanceKm: 1.8,
    rating: 4.8,
    isOpen: true,
    etaMin: 32,
    address: "7, Lakeview Boulevard, Pappampatti, Coimbatore",
    lat: 11.0071,
    lng: 77.0898,
    imageUrl: storeImg("photo-1513519245088-0e12902e5a38"),
  },
  {
    id: "s_decor2",
    name: "Royal Brass Agal & Lamps Emporium",
    category: "home_decor",
    tagline: "Brass Kuthu Vilakku, Agal deepam, divine idols & wall hangings",
    distanceKm: 4.0,
    rating: 4.9,
    isOpen: true,
    etaMin: 34,
    address: "Temple Square, Singanallur Junction, Coimbatore",
    lat: 10.9965,
    lng: 77.0252,
    imageUrl: storeImg("photo-1513519245088-0e12902e5a38"),
  },
  {
    id: "s_decor3",
    name: "Kovai Furnishings & Curtain House",
    category: "home_decor",
    tagline: "Custom velvet drapes, sofa cushions & jute floor rugs",
    distanceKm: 6.1,
    rating: 4.7,
    isOpen: true,
    etaMin: 40,
    address: "Greenway Road, Ondipudur Hub, Coimbatore",
    lat: 10.9919,
    lng: 77.053,
    imageUrl: storeImg("photo-1584100936595-c0654b55a2e2"),
  },

  // ── 12. Fashion Accessories & Gifts ───────────────────────────────────────
  {
    id: "s_acc1",
    name: "Meenakshi Fashion Jewellery & Gift Corner",
    category: "fashion_accessories",
    tagline: "Gold-plated chains, Kammal/Earrings, Thodu, Bangles & Gifts",
    distanceKm: 1.0,
    rating: 4.9,
    isOpen: true,
    etaMin: 24,
    address: "5, Commercial Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0015,
    lng: 77.0868,
    imageUrl: storeImg("photo-1535632066927-ab7c9ab60908"),
  },
  {
    id: "s_acc2",
    name: "Golden Touch Chain & Kammal Gallery",
    category: "fashion_accessories",
    tagline: "Traditional Kammal, Thodu, Antique Chains & Bridal Sets",
    distanceKm: 0.6,
    rating: 4.9,
    isOpen: true,
    etaMin: 19,
    address: "3, Temple Car Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0024,
    lng: 77.0863,
    imageUrl: storeImg("photo-1535632066927-ab7c9ab60908"),
  },
  {
    id: "s_acc3",
    name: "Sparkle Gift Shop & Accessories",
    category: "fashion_accessories",
    tagline: "Customized photo frames, birthday gifts & trendy hair clips",
    distanceKm: 4.2,
    rating: 4.7,
    isOpen: true,
    etaMin: 32,
    address: "High Street, Singanallur Junction, Coimbatore",
    lat: 10.997,
    lng: 77.026,
    imageUrl: storeImg("photo-1549465220-1a8b9238cd48"),
  },
  {
    id: "s_acc4",
    name: "Princess Jhumka & Bangle Palace",
    category: "fashion_accessories",
    tagline: "Kundu jhumka, velvet bangles, bridal thodu & anklet sets",
    distanceKm: 5.6,
    rating: 4.8,
    isOpen: true,
    etaMin: 35,
    address: "Opp. City Bank, Ondipudur Hub, Coimbatore",
    lat: 10.9926,
    lng: 77.0525,
    imageUrl: storeImg("photo-1630019852942-f89202989a59"),
  },

  // ── 13. Bakery ────────────────────────────────────────────────────────────
  {
    id: "s_bakery1",
    name: "Coastline Wood-fired Bakes",
    category: "bakery",
    tagline: "Oven fresh bread, puffs, rusks & buns",
    distanceKm: 1.1,
    rating: 4.9,
    isOpen: true,
    etaMin: 25,
    address: "Main Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0016,
    lng: 77.0873,
    imageUrl: storeImg("photo-1509440159596-0249088772ff"),
  },
  {
    id: "s_bakery2",
    name: "Kovai Hot Oven Bakery & Puffs",
    category: "bakery",
    tagline: "Freshly baked butter croissants, chicken puffs & plum cake",
    distanceKm: 3.7,
    rating: 4.8,
    isOpen: true,
    etaMin: 28,
    address: "Station Road, Singanallur Junction, Coimbatore",
    lat: 10.9984,
    lng: 77.0245,
    imageUrl: storeImg("photo-1555507036-ab1f4038808a"),
  },
  {
    id: "s_bakery3",
    name: "Royal Cake Palace & Sweets",
    category: "bakery",
    tagline: "Custom birthday cakes, chocolate truffles, rusks & cookies",
    distanceKm: 6.3,
    rating: 4.7,
    isOpen: true,
    etaMin: 40,
    address: "Trichy Road, Ondipudur Hub, Coimbatore",
    lat: 10.991,
    lng: 77.0532,
    imageUrl: storeImg("photo-1509440159596-0249088772ff"),
  },

  // ── 14. Book Stalls & Stationery ──────────────────────────────────────────
  {
    id: "s_book1",
    name: "Mega Literature Book House",
    category: "stationery",
    tagline: "Wide range of books, magazines, best sellers & academic books.",
    distanceKm: 0.3,
    rating: 4.6,
    isOpen: true,
    etaMin: 18,
    address: "Market Street 12, Pappampatti Pirivu, Coimbatore",
    lat: 11.0033,
    lng: 77.0861,
    imageUrl: storeImg("photo-1512820790803-83ca734da794"),
  },
  {
    id: "s_book2",
    name: "Paper World Stationery",
    category: "stationery",
    tagline: "Notebooks, pens, art supplies, office & school stationery.",
    distanceKm: 0.5,
    rating: 4.4,
    isOpen: true,
    etaMin: 20,
    address: "24, College Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0039,
    lng: 77.0867,
    imageUrl: storeImg("photo-1583485088034-697b5bc36b92"),
  },
  {
    id: "s_book3",
    name: "Student Corner Books",
    category: "stationery",
    tagline: "Textbooks, reference books & competitive exam materials.",
    distanceKm: 0.7,
    rating: 4.3,
    isOpen: true,
    etaMin: 22,
    address: "8, School Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0042,
    lng: 77.0874,
    imageUrl: storeImg("photo-1497633762265-9d179a990aa6"),
  },
  {
    id: "s_book4",
    name: "Creative Cards & Gifts",
    category: "stationery",
    tagline: "Greeting cards, gift items, wrapping materials & more.",
    distanceKm: 1.1,
    rating: 4.7,
    isOpen: true,
    etaMin: 25,
    address: "15, Fancy Bazaar, Pappampatti Pirivu, Coimbatore",
    lat: 11.005,
    lng: 77.088,
    imageUrl: storeImg("photo-1513519245088-0e12902e5a38"),
  },
];

export const kovilmeduStores: Store[] = [
  {
    id: "s_kovil_bakes",
    name: "Roja Bakes & Sweets (கோவில்மேடு)",
    category: "bakery",
    tagline: "Oven fresh bread, Roja special Mysurpa, chicken puffs & evening snacks",
    distanceKm: 0.3,
    rating: 4.9,
    isOpen: true,
    etaMin: 15,
    address: "Thadagam Main Road, Kovilmedu, Coimbatore",
    lat: 11.0288,
    lng: 76.9260,
    imageUrl: storeImg("photo-1509440159596-0249088772ff"),
  },
  {
    id: "s_kovil_mart",
    name: "Kovilmedu Supermarket & Kirana",
    category: "grocery",
    tagline: "Daily fresh groceries, staples, cooking oil, snacks & household ration",
    distanceKm: 0.4,
    rating: 4.8,
    isOpen: true,
    etaMin: 18,
    address: "Opp. Kovilmedu Arch, Thadagam Road, Coimbatore",
    lat: 11.0282,
    lng: 76.9254,
    imageUrl: storeImg("photo-1604719312566-8912e9227c6a"),
  },
  {
    id: "s_kovil_pala",
    name: "Kovilmedu Organic Palamuthir Nilayam (பழமுதிர்)",
    category: "palamuthir",
    tagline: "Daily fresh organic fruits, tender coconut, hill banana & farm veggies",
    distanceKm: 0.5,
    rating: 4.9,
    isOpen: true,
    etaMin: 18,
    address: "Thadagam Road, Near Bus Stop, Kovilmedu, Coimbatore",
    lat: 11.0291,
    lng: 76.9265,
    imageUrl: storeImg("photo-1610832958506-aa56368176cf"),
  },
  {
    id: "s_kovil_flour",
    name: "Sri Amman Flour & Masala Mill (கோவில்மேடு ஆலை)",
    category: "flour_mill",
    tagline: "Fresh Idli/Dosa batter, milled wheat & freshly ground sambar masala",
    distanceKm: 0.3,
    rating: 4.9,
    isOpen: true,
    etaMin: 15,
    address: "Temple Street, Kovilmedu, Coimbatore",
    lat: 11.0278,
    lng: 76.9250,
    imageUrl: storeImg("photo-1586201375761-83865001e31c"),
  },
  {
    id: "s_kovil_meat",
    name: "Kongu Country Mutton & Chicken Stall (கோவில்மேடு)",
    category: "meat_fish",
    tagline: "Fresh tender Mutton, Nattu Kozhi (Country Chicken) & farm eggs",
    distanceKm: 0.6,
    rating: 4.8,
    isOpen: true,
    etaMin: 20,
    address: "Thadagam Main Road, Kovilmedu, Coimbatore",
    lat: 11.0295,
    lng: 76.9270,
    imageUrl: storeImg("photo-1607623814075-e51df1bdc82f"),
  },
  {
    id: "s_kovil_pharm",
    name: "Kovilmedu Care Medicals & Chemist",
    category: "pharmacy",
    tagline: "24/7 chemist, surgicals, OTC medicines & baby care",
    distanceKm: 0.2,
    rating: 4.8,
    isOpen: true,
    etaMin: 12,
    address: "Junction Arch, Kovilmedu, Coimbatore",
    lat: 11.0286,
    lng: 76.9256,
    imageUrl: storeImg("photo-1587854692152-cbe660dbde88"),
  },
  {
    id: "s_kovil_jewel",
    name: "Meenakshi Fashion Jewellery & Gift Corner (கோவில்மேடு)",
    category: "fashion_accessories",
    tagline: "Gold-plated chains, Kammal/Earrings, Thodu, Bangles & Gifts",
    distanceKm: 0.5,
    rating: 4.9,
    isOpen: true,
    etaMin: 22,
    address: "Bazaar Street, Kovilmedu, Coimbatore",
    lat: 11.0280,
    lng: 76.9262,
    imageUrl: storeImg("photo-1535632066927-ab7c9ab60908"),
  },
  {
    id: "s_kovil_appliances",
    name: "Sri Murugan Kitchen Appliances (பாத்திரம்)",
    category: "kitchen_appliances",
    tagline: "Stainless steel utensils, mixer grinders & pressure cookers",
    distanceKm: 0.7,
    rating: 4.7,
    isOpen: true,
    etaMin: 25,
    address: "Thadagam Road, Kovilmedu, Coimbatore",
    lat: 11.0275,
    lng: 76.9245,
    imageUrl: storeImg("photo-1556911220-e15b29be8c8f"),
  },
  {
    id: "s_kovil_fashion",
    name: "Kovilmedu Readymades & Menswear",
    category: "individual_fashion",
    tagline: "Quality cotton shirts, dhotis, pants & casual wear",
    distanceKm: 0.6,
    rating: 4.7,
    isOpen: true,
    etaMin: 22,
    address: "Main Road, Kovilmedu, Coimbatore",
    lat: 11.0298,
    lng: 76.9261,
    imageUrl: storeImg("photo-1441986300917-64674bd600d8"),
  },
  {
    id: "s_kovil_boutique",
    name: "Vasantham Boutique & Tailoring Studio (கோவில்மேடு)",
    category: "boutiques",
    tagline: "Handloom silk sarees, Aari embroidery work & designer kurtis",
    distanceKm: 0.8,
    rating: 4.9,
    isOpen: true,
    etaMin: 25,
    address: "Thadagam Road, Kovilmedu, Coimbatore",
    lat: 11.0302,
    lng: 76.9275,
    imageUrl: storeImg("photo-1558769132-cb1aea458c5e"),
  },
];

const starterStores: Store[] = [
  {
    id: "s_threadline_studio",
    name: "Threadline Studio",
    category: "boutiques",
    tagline: "Handpicked fabrics, contemporary styles and thoughtful tailoring",
    distanceKm: 0.8,
    rating: 4.9,
    isOpen: true,
    etaMin: 20,
    address: "18 Market Street, Pappampatti, Coimbatore",
    lat: 11.0031,
    lng: 77.0862,
    imageUrl: storeImg("photo-1558769132-cb1aea458c5e"),
  },
  {
    id: "s_pixel_plug",
    name: "Pixel & Plug Showroom",
    category: "showrooms",
    tagline: "Smart screens, everyday electronics and reliable home upgrades",
    distanceKm: 1.1,
    rating: 4.8,
    isOpen: true,
    etaMin: 25,
    address: "5 Garden Avenue, Pappampatti, Coimbatore",
    lat: 11.0047,
    lng: 77.0871,
    imageUrl: storeImg("photo-1555529669-e69e7aa0ba9a"),
  },
  {
    id: "s_hearth_home",
    name: "Hearth & Home Kitchen",
    category: "kitchen_appliances",
    tagline: "Useful cookware and trusted appliances for modern home kitchens",
    distanceKm: 1.6,
    rating: 4.9,
    isOpen: true,
    etaMin: 30,
    address: "42 Temple Road, Singanallur, Coimbatore",
    lat: 11.0018,
    lng: 77.0258,
    imageUrl: storeImg("photo-1556911220-e15b29be8c8f"),
  },
  {
    id: "s_kadalora_jewellery",
    name: "Kadalora Jewellery & Gifts",
    category: "fashion_accessories",
    tagline: "Everyday jewellery, festive accessories and gifts with local character",
    distanceKm: 1.9,
    rating: 4.7,
    isOpen: true,
    etaMin: 25,
    address: "9 Station Road, Ondipudur, Coimbatore",
    lat: 10.9938,
    lng: 77.0523,
    imageUrl: storeImg("photo-1535632066927-ab7c9ab60908"),
  },
  // --- ADDITIONAL COMPREHENSIVE LOCAL SHOPS FOR ALL CATEGORIES ---
  {
    id: "s_supermart_krishna",
    name: "Sri Krishna Departmental Supermarket",
    category: "supermarkets",
    tagline: "Complete monthly family ration, organic staples & multi-departmental household goods",
    distanceKm: 0.5,
    rating: 4.8,
    isOpen: true,
    etaMin: 18,
    address: "12 Trichy Main Road, Coimbatore",
    lat: 11.0055,
    lng: 77.0875,
    imageUrl: storeImg("photo-1604719312566-8912e9227c6a"),
  },
  {
    id: "s_sweets_anandha",
    name: "Anandha Sweet Stall & Savouries",
    category: "sweet_shops",
    tagline: "Melt-in-mouth Mysurpa, Badam Halwa, Mixture, Karasev & festival sweets",
    distanceKm: 0.7,
    rating: 4.9,
    isOpen: true,
    etaMin: 15,
    address: "88 Kovilmedu Junction, Coimbatore",
    lat: 11.0285,
    lng: 76.9268,
    imageUrl: storeImg("photo-1555507036-ab1f4038808a"),
  },
  {
    id: "s_kumbakonam_coffee",
    name: "Kumbakonam Degree Filter Coffee & Tea",
    category: "cafes",
    tagline: "Authentic chicory filter coffee, hot ginger tea, fresh juices & evening tea snacks",
    distanceKm: 0.4,
    rating: 4.9,
    isOpen: true,
    etaMin: 12,
    address: "44 Thadagam Road, Kovilmedu, Coimbatore",
    lat: 11.0290,
    lng: 76.9255,
    imageUrl: storeImg("photo-1517248135467-4c7edcad34c4"),
  },
  {
    id: "s_green_farm_pala",
    name: "Green Farm Organic Produce & Palamuthir",
    category: "fruits_veg",
    tagline: "Farm fresh organic fruits, green leafy vegetables, tender coconut & hill bananas",
    distanceKm: 0.6,
    rating: 4.8,
    isOpen: true,
    etaMin: 16,
    address: "21 Temple Street, Coimbatore",
    lat: 11.0272,
    lng: 76.9248,
    imageUrl: storeImg("photo-1610832958506-aa56368176cf"),
  },
  {
    id: "s_kalyan_fashion",
    name: "Kalyan Menswear & Readymades",
    category: "fashion",
    tagline: "Branded cotton shirts, formal trousers, cotton dhotis & casual jeans",
    distanceKm: 0.9,
    rating: 4.7,
    isOpen: true,
    etaMin: 22,
    address: "102 Crosscut Road, Coimbatore",
    lat: 11.0180,
    lng: 76.9550,
    imageUrl: storeImg("photo-1441986300917-64674bd600d8"),
  },
  {
    id: "s_walkwell_footwear",
    name: "Walkwell Footwear & Leather Shoes",
    category: "footwear",
    tagline: "Formal leather shoes, daily slippers, ethnic sandals & kids sports footwear",
    distanceKm: 1.0,
    rating: 4.7,
    isOpen: true,
    etaMin: 20,
    address: "15 Bazaar Street, Coimbatore",
    lat: 11.0260,
    lng: 76.9240,
    imageUrl: storeImg("photo-1542291026-7eec264c27ff"),
  },
  {
    id: "s_lalitha_jewellery",
    name: "Lalitha Gold-Plated Jewellery & Gifts",
    category: "jewellery",
    tagline: "Traditional Temple Jhumka Kammal, gold-plated chains, silver anklets & bangles",
    distanceKm: 1.2,
    rating: 4.9,
    isOpen: true,
    etaMin: 24,
    address: "77 DB Road, RS Puram, Coimbatore",
    lat: 11.0090,
    lng: 76.9490,
    imageUrl: storeImg("photo-1535632066927-ab7c9ab60908"),
  },
  {
    id: "s_vasanth_electronics",
    name: "Vasanth Electronics & Smart TVs",
    category: "electronics",
    tagline: "4K Smart TVs, home soundbars, double door refrigerators & washing machines",
    distanceKm: 1.4,
    rating: 4.8,
    isOpen: true,
    etaMin: 28,
    address: "50 Avinashi Road, Coimbatore",
    lat: 11.0120,
    lng: 76.9680,
    imageUrl: storeImg("photo-1593784991095-a205069470b6"),
  },
  {
    id: "s_poorvika_mobile",
    name: "Poorvika Mobile Hub & Accessories",
    category: "mobile",
    tagline: "Smartphones, fast chargers, wireless earbuds, back covers & instant mobile repair",
    distanceKm: 0.8,
    rating: 4.8,
    isOpen: true,
    etaMin: 18,
    address: "33 Kovilmedu Main Road, Coimbatore",
    lat: 11.0292,
    lng: 76.9263,
    imageUrl: storeImg("photo-1511707171634-5f897ff02aa9"),
  },
  {
    id: "s_students_stationery",
    name: "Students Corner Books & Stationery",
    category: "books_stationery",
    tagline: "School notebooks, pens, exam files, project art materials & xerox printing",
    distanceKm: 0.3,
    rating: 4.9,
    isOpen: true,
    etaMin: 12,
    address: "5 Near School Gate, Kovilmedu, Coimbatore",
    lat: 11.0284,
    lng: 76.9252,
    imageUrl: storeImg("photo-1531346878377-a5be20888e57"),
  },
  {
    id: "s_nykaa_beauty",
    name: "Nykaa Beauty & Personal Care Hub",
    category: "beauty",
    tagline: "Herbal hair oils, skincare lotions, organic soaps, perfumes & cosmetic sets",
    distanceKm: 1.1,
    rating: 4.8,
    isOpen: true,
    etaMin: 22,
    address: "89 DB Road, RS Puram, Coimbatore",
    lat: 11.0105,
    lng: 76.9495,
    imageUrl: storeImg("photo-1596462502278-27bfdc403348"),
  },
  {
    id: "s_butterfly_kitchen",
    name: "Butterfly Stainless Steel Utensils & Stoves",
    category: "home_kitchen",
    tagline: "Non-stick cookware, pressure cookers, stainless steel vessels & gas stoves",
    distanceKm: 0.9,
    rating: 4.7,
    isOpen: true,
    etaMin: 20,
    address: "62 Mettupalayam Road, Coimbatore",
    lat: 11.0250,
    lng: 76.9380,
    imageUrl: storeImg("photo-1556911220-e15b29be8c8f"),
  },
  {
    id: "s_woodcraft_furniture",
    name: "Woodcraft Furniture & Interior Decor",
    category: "furniture",
    tagline: "Handcrafted brass Agal lamps, designer curtains, sofa sets & home furnishings",
    distanceKm: 1.5,
    rating: 4.9,
    isOpen: true,
    etaMin: 30,
    address: "104 Trichy Road, Coimbatore",
    lat: 10.9980,
    lng: 77.0100,
    imageUrl: storeImg("photo-1584100936595-c0654b55a2e2"),
  },
  {
    id: "s_sriram_hardware",
    name: "Sri Ram Hardware, Tools & Electricals",
    category: "hardware",
    tagline: "LED bulbs, switches, plumbing pipes, paint, hand tools & electrical supplies",
    distanceKm: 0.6,
    rating: 4.8,
    isOpen: true,
    etaMin: 16,
    address: "28 Thadagam Road, Kovilmedu, Coimbatore",
    lat: 11.0280,
    lng: 76.9248,
    imageUrl: storeImg("photo-1581092160607-ee22621dd758"),
  },
  {
    id: "s_champion_sports",
    name: "Champion Sports & Fitness Equipment",
    category: "sports",
    tagline: "Cricket bats, badminton rackets, dumbbells, gym wear & athletic gear",
    distanceKm: 1.3,
    rating: 4.8,
    isOpen: true,
    etaMin: 25,
    address: "71 DB Road, RS Puram, Coimbatore",
    lat: 11.0085,
    lng: 76.9482,
    imageUrl: storeImg("photo-1517649763962-0c623266ddc0"),
  },
  {
    id: "s_little_angels_toys",
    name: "Little Angels Toys & Baby Care",
    category: "toys",
    tagline: "Educational toys, baby diapers, strollers, board games & action figures",
    distanceKm: 0.7,
    rating: 4.9,
    isOpen: true,
    etaMin: 18,
    address: "19 Crosscut Road, Coimbatore",
    lat: 11.0175,
    lng: 76.9542,
    imageUrl: storeImg("photo-1566576912321-d58ddd7a6088"),
  },
  {
    id: "s_archies_gifts",
    name: "Archies Gift Shop & Custom Frames",
    category: "gifts",
    tagline: "Customized photo frames, greeting cards, fancy novelties & party hampers",
    distanceKm: 0.8,
    rating: 4.8,
    isOpen: true,
    etaMin: 20,
    address: "45 DB Road, RS Puram, Coimbatore",
    lat: 11.0078,
    lng: 76.9475,
    imageUrl: storeImg("photo-1549465220-1a8b9238cd48"),
  },
  {
    id: "s_blossom_flowers",
    name: "Blossoms Jasmine & Puja Flower Shop",
    category: "flowers",
    tagline: "Fresh Jasmine garlands (Malli), temple puja flowers & fresh rose bouquets",
    distanceKm: 0.3,
    rating: 4.9,
    isOpen: true,
    etaMin: 10,
    address: "Near Kovilmedu Temple Gate, Coimbatore",
    lat: 11.0287,
    lng: 76.9259,
    imageUrl: storeImg("photo-1563241527-3004b7be0ffd"),
  },
  {
    id: "s_pet_world",
    name: "Pet World Food & Aquarium Centre",
    category: "pet_shops",
    tagline: "Pedigree dog food, cat treats, fish aquariums, bird seeds & pet accessories",
    distanceKm: 1.0,
    rating: 4.8,
    isOpen: true,
    etaMin: 22,
    address: "83 Thadagam Road, Coimbatore",
    lat: 11.0310,
    lng: 76.9280,
    imageUrl: storeImg("photo-1583337130417-3346a1be7dee"),
  },
  {
    id: "s_divine_pooja",
    name: "Divine Agarbatti & Pooja Samagri Store",
    category: "pooja",
    tagline: "Camphor, incense sticks (Agarbatti), brass lamps, pooja oil & kumkum",
    distanceKm: 0.4,
    rating: 4.9,
    isOpen: true,
    etaMin: 14,
    address: "14 Temple Street, Kovilmedu, Coimbatore",
    lat: 11.0276,
    lng: 76.9251,
    imageUrl: storeImg("photo-1608571423902-eed4a5ad8108"),
  },
  {
    id: "s_royal_auto",
    name: "Royal Bike Accessories & Helmets",
    category: "auto",
    tagline: "ISI certified helmets, bike spare parts, motor oil & seat covers",
    distanceKm: 1.1,
    rating: 4.7,
    isOpen: true,
    etaMin: 22,
    address: "95 Mettupalayam Road, Coimbatore",
    lat: 11.0240,
    lng: 76.9370,
    imageUrl: storeImg("photo-1558981806-ec527fa84c39"),
  },
  {
    id: "s_quickfix_repair",
    name: "QuickFix Mobile & Appliance Service",
    category: "repair",
    tagline: "Mobile screen repair, gas stove servicing, mixer motor repair & watch battery replacement",
    distanceKm: 0.5,
    rating: 4.9,
    isOpen: true,
    etaMin: 15,
    address: "37 Kovilmedu Main Road, Coimbatore",
    lat: 11.0289,
    lng: 76.9261,
    imageUrl: storeImg("photo-1581092160607-ee22621dd758"),
  },
  {
    id: "s_express_services",
    name: "Express Print, DTP & Local Services",
    category: "local_services",
    tagline: "Color xerox, DTP printing, key duplication, laundry & tailoring services",
    distanceKm: 0.4,
    rating: 4.8,
    isOpen: true,
    etaMin: 12,
    address: "22 Junction Bus Stand, Kovilmedu, Coimbatore",
    lat: 11.0283,
    lng: 76.9254,
    imageUrl: storeImg("photo-1562654501-a0ccc0fc3fb1"),
  },
];

// Combine all Kovilmedu, legacy, and starter shops into the main store list
export const stores: Store[] = [...kovilmeduStores, ...legacyStores, ...starterStores];

const seedProducts = (storeId: string, cat: StoreCategory): Product[] => {
  const catalogs: Record<StoreCategory, Array<Omit<Product, "id" | "storeId">>> = {
    flour_mill: [
      {
        name: "Fresh Idli & Dosa Batter (மாவு)",
        unit: "1 kg",
        price: 45,
        category: "Fresh Batter",
        imageUrl: img("photo-1586201375761-83865001e31c"),
      },
      {
        name: "Freshly Milled Wheat Atta (சம்பா கோதுமை மாவு)",
        unit: "1 kg",
        price: 58,
        category: "Flour",
        imageUrl: img("photo-1509440159596-0249088772ff"),
      },
      {
        name: "Pure Ragi Flour (கேழ்வரகு மாவு)",
        unit: "500 g",
        price: 35,
        category: "Flour",
        imageUrl: img("photo-1615485290382-441e4d049cb5"),
      },
      {
        name: "Freshly Ground Turmeric Powder (மஞ்சள் தூள்)",
        unit: "200 g",
        price: 60,
        category: "Individual Masalas",
        imageUrl: img("photo-1615485290382-441e4d049cb5"),
      },
      {
        name: "Home Made Sambar Powder (சாம்பார் பொடி)",
        unit: "250 g",
        price: 85,
        category: "Individual Masalas",
        imageUrl: img("photo-1596040033229-a9821ebd058d"),
      },
      {
        name: "Pure Red Chilli Powder (தனி மிளகாய் தூள்)",
        unit: "250 g",
        price: 75,
        category: "Individual Masalas",
        imageUrl: img("photo-1596040033229-a9821ebd058d"),
      },
      {
        name: "Fresh Coriander Powder (மல்லி தூள்)",
        unit: "250 g",
        price: 65,
        category: "Individual Masalas",
        imageUrl: img("photo-1596040033229-a9821ebd058d"),
      },
      {
        name: "Authentic Idli Milagai Podi (இட்லி பொடி)",
        unit: "200 g",
        price: 70,
        category: "Individual Masalas",
        imageUrl: img("photo-1596040033229-a9821ebd058d"),
      },
    ],
    palamuthir: [
      {
        name: "Farm Fresh Alphonso Mangoes",
        unit: "1 kg",
        price: 180,
        category: "Fruits",
        imageUrl: img("photo-1553279768-865429fa0078"),
      },
      {
        name: "Fresh Red Pomegranate (மாதுளை)",
        unit: "1 kg",
        price: 190,
        category: "Fruits",
        imageUrl: img("photo-1610832958506-aa56368176cf"),
      },
      {
        name: "Sweet Tender Coconut (இளநீர்)",
        unit: "1 pc",
        price: 50,
        category: "Fresh Drinks",
        imageUrl: img("photo-1525385133512-2f3bdd039054"),
      },
      {
        name: "Fresh Country Tomatoes (தக்காளி)",
        unit: "1 kg",
        price: 38,
        category: "Vegetables",
        imageUrl: img("photo-1592924357228-91a4daadcfea"),
      },
      {
        name: "Fresh Green Spinach Bunch (கீரைகள்)",
        unit: "2 bunches",
        price: 30,
        category: "Vegetables",
        imageUrl: img("photo-1576045057995-568f588f82fb"),
      },
    ],
    meat_fish: [
      {
        name: "Tender Mutton Curry Cut (ஆட்டு இறைச்சி)",
        unit: "500 g",
        price: 440,
        category: "Mutton",
        imageUrl: img("photo-1607623814075-e51df1bdc82f"),
      },
      {
        name: "Fresh Country Chicken Skinless (நாட்டுக் கோழி)",
        unit: "1 kg",
        price: 260,
        category: "Chicken",
        imageUrl: img("photo-1587593810167-a84920ea0781"),
      },
      {
        name: "Fresh Seer Fish / Vanjaram Slices (வஞ்சரம் மீன்)",
        unit: "500 g",
        price: 580,
        category: "Fish",
        imageUrl: img("photo-1534422298391-e4f8c172dddb"),
      },
      {
        name: "Tiger Prawns Cleaned (இறால்)",
        unit: "500 g",
        price: 390,
        category: "Seafood",
        imageUrl: img("photo-1565680018434-b513d5e5fd47"),
      },
      {
        name: "Farm Fresh Country Eggs (நாட்டு முட்டை)",
        unit: "6 pcs",
        price: 84,
        category: "Eggs",
        imageUrl: img("photo-1582722872445-44dc5f7e3c8f"),
      },
    ],
    fashion_accessories: [
      {
        name: "Gold-Plated Designer Chain (செயின்)",
        unit: "1 pc",
        price: 380,
        category: "Jewellery",
        imageUrl: img("photo-1535632066927-ab7c9ab60908"),
      },
      {
        name: "Traditional Temple Jhumka Kammal (கம்மல் / தோடு)",
        unit: "1 pair",
        price: 220,
        category: "Earrings",
        imageUrl: img("photo-1630019852942-f89202989a59"),
      },
      {
        name: "Silk Thread Bangle Set (வளையல்கள்)",
        unit: "Set of 12",
        price: 260,
        category: "Bangles",
        imageUrl: img("photo-1611591475777-233cd7579624"),
      },
      {
        name: "Handcrafted Gift Hamper Box",
        unit: "1 set",
        price: 490,
        category: "Gifts",
        imageUrl: img("photo-1549465220-1a8b9238cd48"),
      },
    ],
    boutiques: [
      {
        name: "Kanchipuram Soft Silk Saree",
        unit: "1 pc",
        price: 3450,
        category: "Sarees",
        imageUrl: img("photo-1610030469983-98e550d6193c"),
      },
      {
        name: "Handloom Cotton Kurti & Dupatta Set",
        unit: "1 set",
        price: 1150,
        category: "Kurtis",
        imageUrl: img("photo-1583391733956-6c78276477e2"),
      },
      {
        name: "Custom Embroidery Designer Blouse Stitching",
        unit: "1 pc",
        price: 850,
        category: "Stitching",
        imageUrl: img("photo-1537633552985-df8429e8048b"),
      },
    ],
    showrooms: [
      {
        name: 'Smart 4K Ultra HD LED TV 43"',
        unit: "1 unit",
        price: 22990,
        category: "Electronics",
        imageUrl: img("photo-1593784991095-a205069470b6"),
      },
      {
        name: "Pure Silk Kanchipuram Bridal Wedding Saree",
        unit: "1 pc",
        price: 7800,
        category: "Textiles",
        imageUrl: img("photo-1610030469983-98e550d6193c"),
      },
    ],
    fast_fashion: [
      {
        name: "Pure Cotton Casual Slim Fit Shirt",
        unit: "1 pc",
        price: 699,
        category: "Men",
        imageUrl: img("photo-1489987707025-afc232f7ea0f"),
      },
      {
        name: "High-Rise Stretch Denim Jeans",
        unit: "1 pc",
        price: 999,
        category: "Women",
        imageUrl: img("photo-1541099649105-f69ad21f3246"),
      },
    ],
    individual_fashion: [
      {
        name: "Traditional Pure Cotton Dhoti & Shirt Combo",
        unit: "1 set",
        price: 899,
        category: "Traditional",
        imageUrl: img("photo-1441986300917-64674bd600d8"),
      },
      {
        name: "Casual Checkered Men Cotton Shirt",
        unit: "1 pc",
        price: 599,
        category: "Menswear",
        imageUrl: img("photo-1489987707025-afc232f7ea0f"),
      },
      {
        name: "Men Formal White Full Sleeve Linen Shirt",
        unit: "1 pc",
        price: 799,
        category: "Shirts",
        imageUrl: img("photo-1489987707025-afc232f7ea0f"),
      },
      {
        name: "Men Regular Fit Denim Jeans",
        unit: "1 pc",
        price: 999,
        category: "Jeans",
        imageUrl: img("photo-1541099649105-f69ad21f3246"),
      },
      {
        name: "Printed Cotton Round Neck T-Shirt",
        unit: "1 pc",
        price: 349,
        category: "T-Shirts",
        imageUrl: img("photo-1521572267360-ee0c2909d518"),
      },
    ],
    kitchen_appliances: [
      {
        name: "Preethi 750W 3-Jar Mixer Grinder",
        unit: "1 unit",
        price: 3290,
        category: "Appliances",
        imageUrl: img("photo-1584990347449-716c15a3a17a"),
      },
      {
        name: "Hawkins 3 Litre Stainless Steel Pressure Cooker",
        unit: "1 unit",
        price: 1450,
        category: "Cookware",
        imageUrl: img("photo-1584990347449-716c15a3a17a"),
      },
    ],
    home_decor: [
      {
        name: "Traditional Handcrafted Brass Agal Lamp (குத்துவிளக்கு)",
        unit: "1 pair",
        price: 650,
        category: "Decor",
        imageUrl: img("photo-1513519245088-0e12902e5a38"),
      },
      {
        name: "Velvet Designer Cushion Covers (Set of 5)",
        unit: "5 pcs",
        price: 399,
        category: "Furnishings",
        imageUrl: img("photo-1584100936595-c0654b55a2e2"),
      },
    ],
    pharmacy: [
      {
        name: "Paracetamol 500mg OTC",
        unit: "10 tabs",
        price: 22,
        category: "OTC Medicines",
        imageUrl: img("photo-1584308666744-24d5c474f2ae"),
      },
      {
        name: "Pulse Oximeter & Digital Monitor",
        unit: "1 pc",
        price: 450,
        category: "Wellness",
        imageUrl: img("photo-1584362917165-526a968579e8"),
      },
    ],
    stationery: [
      {
        name: "Classmate A4 Ruled Notebooks (Pack of 6)",
        unit: "6 pcs",
        price: 240,
        category: "Notebooks",
        imageUrl: img("photo-1531346878377-a5be20888e57"),
      },
      {
        name: "Gel Pens Blue Set",
        unit: "5 pcs",
        price: 60,
        category: "Pens",
        imageUrl: img("photo-1583485088034-697b5bc36b92"),
      },
    ],
    bakery: [
      {
        name: "Roja Special Butter Mysurpa",
        unit: "250 g",
        price: 140,
        category: "Sweets",
        imageUrl: img("photo-1555507036-ab1f4038808a"),
      },
      {
        name: "Roja Oven Fresh Butter Roti",
        unit: "4 pcs",
        price: 40,
        category: "Bakes",
        imageUrl: img("photo-1509440159596-0249088772ff"),
      },
      {
        name: "Fresh Oven Butter Croissant",
        unit: "1 pc",
        price: 65,
        category: "Bakes",
        imageUrl: img("photo-1555507036-ab1f4038808a"),
      },
      {
        name: "Crispy Egg Puff & Chicken Puff",
        unit: "2 pcs",
        price: 70,
        category: "Savouries",
        imageUrl: img("photo-1509440159596-0249088772ff"),
      },
      {
        name: "Whole Wheat Bread Loaf & Toast",
        unit: "400 g",
        price: 45,
        category: "Bakes",
        imageUrl: img("photo-1509440159596-0249088772ff"),
      },
      {
        name: "Chocolate Truffle Cake Slice",
        unit: "1 pc",
        price: 95,
        category: "Cakes",
        imageUrl: img("photo-1555507036-ab1f4038808a"),
      },
    ],
    grocery: [
      {
        name: "Sona Masoori Premium Rice (பொன்னி அரிசி)",
        unit: "5 kg",
        price: 340,
        category: "Staples",
        imageUrl: img("photo-1586201375761-83865001e31c"),
      },
      {
        name: "Cold Pressed Pure Coconut Oil (தேங்காய் எண்ணெய்)",
        unit: "1 Litre",
        price: 240,
        category: "Oils",
        imageUrl: img("photo-1604719312566-8912e9227c6a"),
      },
      {
        name: "Organic Unpolished Toor Dal (துவரம் பருப்பு)",
        unit: "1 kg",
        price: 145,
        category: "Pulses",
        imageUrl: img("photo-1586201375761-83865001e31c"),
      },
      {
        name: "Premium Whole Urad Dal (உளுந்தம் பருப்பு)",
        unit: "1 kg",
        price: 135,
        category: "Pulses",
        imageUrl: img("photo-1586201375761-83865001e31c"),
      },
      {
        name: "Natural Country Jaggery Powder (நாட்டுச் சர்க்கரை)",
        unit: "1 kg",
        price: 90,
        category: "Staples",
        imageUrl: img("photo-1615485290382-441e4d049cb5"),
      },
      {
        name: "Pure Farm Cow Ghee (பசும் நெய்)",
        unit: "500 ml",
        price: 320,
        category: "Dairy & Ghee",
        imageUrl: img("photo-1604719312566-8912e9227c6a"),
      },
    ],
    restaurants: [
      {
        name: "Special South Indian Meals",
        unit: "1 Plate",
        price: 150,
        category: "Meals",
        imageUrl: img("photo-1626777552726-4a6b54c97e46"),
      },
      {
        name: "Chettinad Chicken Biryani",
        unit: "1 Bucket",
        price: 280,
        category: "Biryani",
        imageUrl: img("photo-1563379091339-03b21ab4a4f8"),
      },
    ],
    supermarkets: [
      {
        name: "Sona Masoori Rice (பொன்னி அரிசி)",
        unit: "10 kg",
        price: 680,
        category: "Staples",
        imageUrl: img("photo-1586201375761-83865001e31c"),
      },
      {
        name: "Fortune Sunflower Oil Pouch",
        unit: "1 Litre",
        price: 135,
        category: "Oils",
        imageUrl: img("photo-1604719312566-8912e9227c6a"),
      },
    ],
    sweet_shops: [
      {
        name: "Special Melt-in-Mouth Ghee Mysurpa",
        unit: "250 g",
        price: 160,
        category: "Sweets",
        imageUrl: img("photo-1555507036-ab1f4038808a"),
      },
      {
        name: "Traditional Kara Sev & Special Mixture",
        unit: "250 g",
        price: 85,
        category: "Savouries",
        imageUrl: img("photo-1509440159596-0249088772ff"),
      },
    ],
    cafes: [
      {
        name: "Authentic Kumbakonam Filter Coffee",
        unit: "1 Cup",
        price: 25,
        category: "Coffee",
        imageUrl: img("photo-1517248135467-4c7edcad34c4"),
      },
      {
        name: "Fresh Watermelon & Orange Juice",
        unit: "350 ml",
        price: 60,
        category: "Juices",
        imageUrl: img("photo-1525385133512-2f3bdd039054"),
      },
    ],
    fruits_veg: [
      {
        name: "Fresh Farm Red Apples",
        unit: "1 kg",
        price: 190,
        category: "Fruits",
        imageUrl: img("photo-1610832958506-aa56368176cf"),
      },
      {
        name: "Organic Spinach & Greens Mix",
        unit: "3 bunches",
        price: 45,
        category: "Vegetables",
        imageUrl: img("photo-1576045057995-568f588f82fb"),
      },
    ],
    fashion: [
      {
        name: "Men Pure Cotton Casual Shirt",
        unit: "1 pc",
        price: 699,
        category: "Shirts",
        imageUrl: img("photo-1489987707025-afc232f7ea0f"),
      },
      {
        name: "Men Slim Fit Formal Linen Shirt",
        unit: "1 pc",
        price: 999,
        category: "Shirts",
        imageUrl: img("photo-1489987707025-afc232f7ea0f"),
      },
      {
        name: "Traditional White Ramraj Dhoti & Shirt Set",
        unit: "1 set",
        price: 899,
        category: "Dhotis & Shirts",
        imageUrl: img("photo-1441986300917-64674bd600d8"),
      },
      {
        name: "Men Round Neck Cotton T-Shirt",
        unit: "1 pc",
        price: 399,
        category: "T-Shirts",
        imageUrl: img("photo-1521572267360-ee0c2909d518"),
      },
      {
        name: "Men Slim Fit Stretchable Denim Jeans",
        unit: "1 pc",
        price: 1199,
        category: "Jeans",
        imageUrl: img("photo-1541099649105-f69ad21f3246"),
      },
      {
        name: "Women Cotton Floral Printed Kurti",
        unit: "1 pc",
        price: 549,
        category: "Kurtis",
        imageUrl: img("photo-1583391733956-6c78276477e2"),
      },
    ],
    footwear: [
      {
        name: "Men Leather Formal Shoes",
        unit: "1 pair",
        price: 1299,
        category: "Footwear",
        imageUrl: img("photo-1542291026-7eec264c27ff"),
      },
      {
        name: "Women Ethnic Leather Sandals",
        unit: "1 pair",
        price: 499,
        category: "Footwear",
        imageUrl: img("photo-1542291026-7eec264c27ff"),
      },
    ],
    jewellery: [
      {
        name: "Temple Design Jhumka Kammal",
        unit: "1 pair",
        price: 350,
        category: "Jewellery",
        imageUrl: img("photo-1630019852942-f89202989a59"),
      },
      {
        name: "Gold-Plated Traditional Chain",
        unit: "1 pc",
        price: 420,
        category: "Jewellery",
        imageUrl: img("photo-1535632066927-ab7c9ab60908"),
      },
    ],
    electronics: [
      {
        name: "4K Smart LED Television 43 Inch",
        unit: "1 unit",
        price: 22990,
        category: "TV",
        imageUrl: img("photo-1593784991095-a205069470b6"),
      },
      {
        name: "Surround Soundbar 120W Speaker",
        unit: "1 unit",
        price: 4990,
        category: "Audio",
        imageUrl: img("photo-1545454675-3531b543be5d"),
      },
    ],
    mobile: [
      {
        name: "Type-C 65W Fast Charger Adapter",
        unit: "1 unit",
        price: 699,
        category: "Chargers",
        imageUrl: img("photo-1511707171634-5f897ff02aa9"),
      },
      {
        name: "True Wireless Bluetooth Earbuds",
        unit: "1 pair",
        price: 1299,
        category: "Earbuds",
        imageUrl: img("photo-1511707171634-5f897ff02aa9"),
      },
    ],
    books_stationery: [
      {
        name: "Classmate A4 Long Notebooks (Pack of 6)",
        unit: "6 pcs",
        price: 250,
        category: "School",
        imageUrl: img("photo-1531346878377-a5be20888e57"),
      },
      {
        name: "Smooth Gel Ballpoint Pens (Set of 5)",
        unit: "5 pcs",
        price: 50,
        category: "Office",
        imageUrl: img("photo-1583485088034-697b5bc36b92"),
      },
    ],
    beauty: [
      {
        name: "Herbal Coconut Hair Oil",
        unit: "200 ml",
        price: 110,
        category: "Hair Care",
        imageUrl: img("photo-1596462502278-27bfdc403348"),
      },
      {
        name: "Moisturizing Face & Body Lotion",
        unit: "250 ml",
        price: 220,
        category: "Bath & Body",
        imageUrl: img("photo-1596462502278-27bfdc403348"),
      },
    ],
    home_kitchen: [
      {
        name: "Stainless Steel 3-Tier Lunch Box",
        unit: "1 pc",
        price: 450,
        category: "Kitchen",
        imageUrl: img("photo-1556911220-e15b29be8c8f"),
      },
      {
        name: "Non-Stick Frying Pan 24cm",
        unit: "1 pc",
        price: 650,
        category: "Cookware",
        imageUrl: img("photo-1556911220-e15b29be8c8f"),
      },
    ],
    furniture: [
      {
        name: "Traditional Handcrafted Brass Agal Lamp",
        unit: "1 pair",
        price: 650,
        category: "Home Decor",
        imageUrl: img("photo-1513519245088-0e12902e5a38"),
      },
      {
        name: "Velvet Cushion Covers (Set of 5)",
        unit: "5 pcs",
        price: 399,
        category: "Furnishings",
        imageUrl: img("photo-1584100936595-c0654b55a2e2"),
      },
    ],
    hardware: [
      {
        name: "Havells 9W Cool Daylight LED Bulbs (Pack of 3)",
        unit: "3 pcs",
        price: 280,
        category: "Electrical",
        imageUrl: img("photo-1581092160607-ee22621dd758"),
      },
      {
        name: "Heavy Duty Multi-Purpose Hand Tool Kit",
        unit: "1 set",
        price: 750,
        category: "Tools",
        imageUrl: img("photo-1581092160607-ee22621dd758"),
      },
    ],
    sports: [
      {
        name: "Kashmir Willow Cricket Bat Size 6",
        unit: "1 pc",
        price: 1150,
        category: "Cricket",
        imageUrl: img("photo-1517649763962-0c623266ddc0"),
      },
      {
        name: "Yonex Badminton Racket & Shuttlecock Set",
        unit: "1 set",
        price: 890,
        category: "Badminton",
        imageUrl: img("photo-1517649763962-0c623266ddc0"),
      },
    ],
    toys: [
      {
        name: "Wooden Educational Building Blocks Toy",
        unit: "1 set",
        price: 499,
        category: "Toys",
        imageUrl: img("photo-1566576912321-d58ddd7a6088"),
      },
      {
        name: "Soft Baby Care Diapers Large (Pack of 30)",
        unit: "30 pcs",
        price: 420,
        category: "Baby",
        imageUrl: img("photo-1566576912321-d58ddd7a6088"),
      },
    ],
    gifts: [
      {
        name: "Customized Wooden Photo Frame",
        unit: "1 pc",
        price: 350,
        category: "Gifting",
        imageUrl: img("photo-1549465220-1a8b9238cd48"),
      },
      {
        name: "Handmade Festive Greeting Card & Hamper",
        unit: "1 set",
        price: 299,
        category: "Gifting",
        imageUrl: img("photo-1549465220-1a8b9238cd48"),
      },
    ],
    flowers: [
      {
        name: "Fresh Jasmine Flower Garland (மல்லிகைப் பூ சரங்கள்)",
        unit: "1 meter",
        price: 80,
        category: "Garlands",
        imageUrl: img("photo-1563241527-3004b7be0ffd"),
      },
      {
        name: "Red Rose Bouquet for Occasions",
        unit: "1 bouquet",
        price: 250,
        category: "Bouquets",
        imageUrl: img("photo-1563241527-3004b7be0ffd"),
      },
    ],
    pet_shops: [
      {
        name: "Pedigree Adult Dog Food Chicken & Vegetables",
        unit: "1.2 kg",
        price: 320,
        category: "Dog Food",
        imageUrl: img("photo-1583337130417-3346a1be7dee"),
      },
      {
        name: "Colorful Fish Aquarium Glass Bowl & Feed",
        unit: "1 set",
        price: 450,
        category: "Aquarium",
        imageUrl: img("photo-1583337130417-3346a1be7dee"),
      },
    ],
    pooja: [
      {
        name: "Pure Natural Camphor (பச்சைக் கற்பூரம்)",
        unit: "100 g",
        price: 90,
        category: "Camphor",
        imageUrl: img("photo-1608571423902-eed4a5ad8108"),
      },
      {
        name: "Fragrant Sandal Incense Agarbatti Sticks",
        unit: "Pack of 3",
        price: 75,
        category: "Incense",
        imageUrl: img("photo-1608571423902-eed4a5ad8108"),
      },
    ],
    auto: [
      {
        name: "ISI Certified Full-Face Bike Helmet",
        unit: "1 pc",
        price: 890,
        category: "Helmets",
        imageUrl: img("photo-1558981806-ec527fa84c39"),
      },
      {
        name: "Castrol 4T 2-Wheeler Engine Oil 20W40",
        unit: "1 Litre",
        price: 380,
        category: "Motor Oil",
        imageUrl: img("photo-1558981806-ec527fa84c39"),
      },
    ],
    repair: [
      {
        name: "Mobile Screen Guard Glass Replacement Service",
        unit: "1 service",
        price: 150,
        category: "Mobile Repair",
        imageUrl: img("photo-1581092160607-ee22621dd758"),
      },
      {
        name: "Gas Stove Cleaning & Burner Service",
        unit: "1 service",
        price: 250,
        category: "Stove Service",
        imageUrl: img("photo-1581092160607-ee22621dd758"),
      },
    ],
    local_services: [
      {
        name: "High Speed A4 Color Xerox & Printing",
        unit: "10 pages",
        price: 40,
        category: "Printing",
        imageUrl: img("photo-1562654501-a0ccc0fc3fb1"),
      },
      {
        name: "Duplicate Door & Bike Key Duplication",
        unit: "1 key",
        price: 60,
        category: "Key Duplication",
        imageUrl: img("photo-1562654501-a0ccc0fc3fb1"),
      },
    ],
  };
  return (catalogs[cat] || catalogs.palamuthir).map((p, i) => ({
    ...p,
    id: `${storeId}-p${i}`,
    storeId,
  }));
};

export const productsByStore: Record<string, Product[]> = Object.fromEntries(
  stores.map((s) => [s.id, seedProducts(s.id, s.category)]),
);

export const getStore = (id: string) =>
  stores.find((s) => s.id === id) ?? {
    ...APPROVED_STORE,
    id,
    name: id.startsWith("s_") ? id.replace("s_", "").replace(/_/g, " ") : "Local Shore Shop",
  };
