export type StoreCategory =
  | "showrooms"
  | "boutiques"
  | "fast_fashion"
  | "individual_fashion"
  | "flour_mill"
  | "palamuthir"
  | "meat_fish"
  | "pharmacy"
  | "stationery"
  | "home_decor"
  | "kitchen_appliances"
  | "fashion_accessories"
  | "bakery"
  | "grocery"
  | "restaurants";

export interface Store {
  id: string;
  name: string;
  category: StoreCategory;
  tagline: string;
  distanceKm: number;
  rating: number;
  isOpen: boolean;
  etaMin: number;
  address: string;
  lat: number;
  lng: number;
  imageUrl: string;
}

export interface DeliveryCategory {
  id: string;
  label: string;
  imageUrl: string;
  filter?: StoreCategory;
}

const catImg = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=300&q=75`;
const storeImg = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=75`;
const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=300&q=75`;

export const APPROVED_STORE: Store = {
  id: "approved-catalog",
  name: "Verified local products",
  category: "palamuthir",
  tagline: "Approved by Seller Hub",
  distanceKm: 2,
  rating: 5,
  isOpen: true,
  etaMin: 30,
  address: "Available from approved local vendors",
  lat: 11.0028,
  lng: 77.0865,
  imageUrl: catImg("photo-1542838132-92c53300491e"),
};

export const deliveryCategories: DeliveryCategory[] = [
  {
    id: "palamuthir",
    label: "Palamuthir Nilayam (பழமுதிர்)",
    imageUrl: catImg("photo-1610832958506-aa56368176cf"),
    filter: "palamuthir",
  },
  {
    id: "flour_mill",
    label: "Flour Mill (மாவு ஆலை)",
    imageUrl: catImg("photo-1586201375761-83865001e31c"),
    filter: "flour_mill",
  },
  {
    id: "meat_fish",
    label: "Meat, Fish & Chicken",
    imageUrl: catImg("photo-1607623814075-e51df1bdc82f"),
    filter: "meat_fish",
  },
  {
    id: "fashion_accessories",
    label: "Chain, Kammal & Gifts",
    imageUrl: catImg("photo-1535632066927-ab7c9ab60908"),
    filter: "fashion_accessories",
  },
  {
    id: "boutiques",
    label: "Designer Boutiques",
    imageUrl: catImg("photo-1558769132-cb1aea458c5e"),
    filter: "boutiques",
  },
  {
    id: "fast_fashion",
    label: "Fast Fashion (Branded)",
    imageUrl: catImg("photo-1489987707025-afc232f7ea0f"),
    filter: "fast_fashion",
  },
  {
    id: "showrooms",
    label: "Showrooms",
    imageUrl: catImg("photo-1555529669-e69e7aa0ba9a"),
    filter: "showrooms",
  },
  {
    id: "kitchen_appliances",
    label: "Kitchen Appliances (பாத்திரம்)",
    imageUrl: catImg("photo-1556911220-e15b29be8c8f"),
    filter: "kitchen_appliances",
  },
  {
    id: "home_decor",
    label: "Interior & Home Decor",
    imageUrl: catImg("photo-1513519245088-0e12902e5a38"),
    filter: "home_decor",
  },
  {
    id: "individual_fashion",
    label: "Individual Fashion",
    imageUrl: catImg("photo-1441986300917-64674bd600d8"),
    filter: "individual_fashion",
  },
  {
    id: "pharmacy",
    label: "Individual Pharmacy",
    imageUrl: catImg("photo-1587854692152-cbe660dbde88"),
    filter: "pharmacy",
  },
  {
    id: "stationery",
    label: "Book Stall & Stationery",
    imageUrl: catImg("photo-1519682337058-a94d519337bc"),
    filter: "stationery",
  },
];

export interface Product {
  id: string;
  storeId: string;
  name: string;
  unit: string;
  price: number;
  category: string;
  imageUrl?: string;
  stock?: number;
}

export const categoryColor: Record<StoreCategory, string> = {
  showrooms: "#4F46E5",
  boutiques: "#DB2777",
  fast_fashion: "#7C3AED",
  individual_fashion: "#E11D48",
  flour_mill: "#D97706",
  palamuthir: "#16A34A",
  meat_fish: "#DC2626",
  pharmacy: "#0284C7",
  stationery: "#CA8A04",
  home_decor: "#059669",
  kitchen_appliances: "#475569",
  fashion_accessories: "#EC4899",
  bakery: "#B36A3E",
  grocery: "#059669",
  restaurants: "#E11D48",
};

export const categoryLabel: Record<StoreCategory, string> = {
  showrooms: "Showrooms",
  boutiques: "Designer Boutiques",
  fast_fashion: "Fast Fashion (Branded)",
  individual_fashion: "Individual Fashion",
  flour_mill: "Flour & Masala Mill (மாவு & மசாலா ஆலை)",
  palamuthir: "Palamuthir Nilayam (பழமுதிர்)",
  meat_fish: "Meat, Fish & Chicken",
  pharmacy: "Individual Pharmacy",
  stationery: "Book Stalls & Stationery",
  home_decor: "Interior & Home Decor",
  kitchen_appliances: "Kitchen Appliances",
  fashion_accessories: "Fashion Accessories & Gifts",
  bakery: "Bakery",
  grocery: "Kirana & Grocery",
  restaurants: "Restaurants",
};

const legacyStores: Store[] = [
  {
    id: "s_roja_bakes",
    name: "Roja Bakes & Sweets (பாப்பம்பட்டி பிரிவு)",
    category: "bakery",
    tagline: "Oven fresh bread, Roja special Mysurpa, Roti, Puffs & Sweets",
    distanceKm: 0.4,
    rating: 4.9,
    isOpen: true,
    etaMin: 15,
    address: "Main Road, Pappampatti Pirivu, Coimbatore",
    lat: 10.999,
    lng: 76.974,
    imageUrl: storeImg("photo-1509440159596-0249088772ff"),
  },
  {
    id: "s_roja_mart",
    name: "Roja Supermarket & Kirana",
    category: "grocery",
    tagline: "Daily fresh groceries, Roja atta, snacks & household essentials",
    distanceKm: 0.6,
    rating: 4.8,
    isOpen: true,
    etaMin: 18,
    address: "Pappampatti Pirivu Bus Stop, Coimbatore",
    lat: 10.9985,
    lng: 76.973,
    imageUrl: storeImg("photo-1604719312566-8912e9227c6a"),
  },
  // ── 0. Swiggy Featured Restaurants & Bakes ──────────────────────────────────────
  {
    id: "s_haribhavanam",
    name: "Haribhavanam",
    category: "meat_fish",
    tagline: "Authentic South Indian Non-Veg, Meals, Biryani & Chettinad Specials",
    distanceKm: 0.8,
    rating: 4.9,
    isOpen: true,
    etaMin: 20,
    address: "Trichy Road, Sungam Junction, Coimbatore",
    lat: 10.9995,
    lng: 76.9745,
    imageUrl: storeImg("photo-1555396273-367ea4eb4db5"),
  },
  {
    id: "s_terminal2",
    name: "Terminal 2 (Unit of Haribhavanam)",
    category: "meat_fish",
    tagline: "Gourmet Burgers, Harissa Wraps, Kebabs & Continental Delights",
    distanceKm: 1.2,
    rating: 4.8,
    isOpen: true,
    etaMin: 22,
    address: "Race Course Road, Coimbatore",
    lat: 10.998,
    lng: 76.971,
    imageUrl: storeImg("photo-1568901346375-23c9450c58cd"),
  },
  // ── 1. Fresh Stalls & Bakes ────────────────────────────────────────────────────────────
  {
    id: "s_paap1",
    name: "Sri Krishna Sweets & Bakery (பாப்பம்பட்டி பிரிவு)",
    category: "bakery",
    tagline: "Fresh Mysurpa, hot savouries, tea, puffs & daily bakery items",
    distanceKm: 0.3,
    rating: 4.9,
    isOpen: true,
    etaMin: 15,
    address: "Pappampatti Pirivu Junction, Trichy Road, Coimbatore",
    lat: 11.0028,
    lng: 77.0865,
    imageUrl: storeImg("photo-1586201375761-83865001e31c"),
  },
  {
    id: "s_kiran1",
    name: "Anand Kirana Provision Store",
    category: "flour_mill",
    tagline: "Fresh batter, pulses, coconut oil & daily kitchen ration",
    distanceKm: 0.4,
    rating: 4.7,
    isOpen: true,
    etaMin: 18,
    address: "12, Trichy Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0027,
    lng: 77.086,
    imageUrl: storeImg("photo-1604719312566-8912e9227c6a"),
  },
  {
    id: "s_groc2",
    name: "Singanallur Super Groceries & Rice Mart",
    category: "flour_mill",
    tagline: "Bulk Sona Masoori rice, organic pulses, cold pressed oil & spices",
    distanceKm: 3.3,
    rating: 4.8,
    isOpen: true,
    etaMin: 28,
    address: "Trichy Road, Singanallur Junction, Coimbatore",
    lat: 10.9982,
    lng: 77.0255,
    imageUrl: storeImg("photo-1578916171728-46686eac8d58"),
  },
  {
    id: "s_groc3",
    name: "Ondipudur Daily Fresh Supermarket",
    category: "palamuthir",
    tagline: "Complete family fresh produce, fruits & dairy items",
    distanceKm: 5.5,
    rating: 4.7,
    isOpen: true,
    etaMin: 35,
    address: "Main Road, Ondipudur Hub, Coimbatore",
    lat: 10.9925,
    lng: 77.0528,
    imageUrl: storeImg("photo-1542838132-92c53300491e"),
  },

  // ── 2. Palamuthir ─────────────────────────────────────────────────────────
  {
    id: "s_paap2",
    name: "Pappampatti Organic Super Mart & Fruits (பழமுதிர்)",
    category: "palamuthir",
    tagline: "Daily fresh organic fruits, tender coconut, hill banana & farm veggies",
    distanceKm: 0.5,
    rating: 4.8,
    isOpen: true,
    etaMin: 18,
    address: "Opp. IOC Fuel Station, Pappampatti Pirivu, Coimbatore",
    lat: 11.0035,
    lng: 77.0872,
    imageUrl: storeImg("photo-1610832958506-aa56368176cf"),
  },
  {
    id: "s_pala1",
    name: "Kovai Pazhamudir Nilayam (பழமுதிர்)",
    category: "palamuthir",
    tagline: "Daily fresh organic fruits, tender coconut & veggies",
    distanceKm: 0.7,
    rating: 4.8,
    isOpen: true,
    etaMin: 20,
    address: "88, Trichy Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0038,
    lng: 77.0875,
    imageUrl: storeImg("photo-1610832958506-aa56368176cf"),
  },
  {
    id: "s_pala2",
    name: "Green Coast Organic Fruit & Veggie Bazaar",
    category: "palamuthir",
    tagline: "Organic mangoes, pomegranate, fresh greens & tender coconut",
    distanceKm: 1.2,
    rating: 4.9,
    isOpen: true,
    etaMin: 22,
    address: "55, Garden Avenue, Pappampatti Pirivu, Coimbatore",
    lat: 11.0055,
    lng: 77.0869,
    imageUrl: storeImg("photo-1610832958506-aa56368176cf"),
  },
  {
    id: "s_pala3",
    name: "Singanallur Fresh Farm Palamuthir",
    category: "palamuthir",
    tagline: "Farm fresh vegetables, apples, avocados & hydroponic greens",
    distanceKm: 3.6,
    rating: 4.7,
    isOpen: true,
    etaMin: 30,
    address: "Kamraj Road, Singanallur Junction, Coimbatore",
    lat: 10.9978,
    lng: 77.0262,
    imageUrl: storeImg("photo-1540420773420-3366772f4999"),
  },

  // ── 3. Flour Mill ─────────────────────────────────────────────────────────
  {
    id: "s_paap3",
    name: "Sri Selvamani Flour & Masala Mill (பாப்பம்பட்டி மாவு ஆலை)",
    category: "flour_mill",
    tagline: "Fresh Idli/Dosa batter, milled wheat & freshly ground sambar masala",
    distanceKm: 0.4,
    rating: 4.9,
    isOpen: true,
    etaMin: 16,
    address: "Selvapuram Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0019,
    lng: 77.0858,
    imageUrl: storeImg("photo-1586201375761-83865001e31c"),
  },
  {
    id: "s_flour1",
    name: "Sri Lakshmi Flour & Masala Mill (மாவு & மசாலா ஆலை)",
    category: "flour_mill",
    tagline: "Fresh Idli/Dosa batter, milled wheat & freshly ground individual masalas",
    distanceKm: 0.5,
    rating: 4.9,
    isOpen: true,
    etaMin: 18,
    address: "14, Temple Car Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0025,
    lng: 77.0862,
    imageUrl: storeImg("photo-1586201375761-83865001e31c"),
  },
  {
    id: "s_flour2",
    name: "Amman Maavu Mill & Pure Spices",
    category: "flour_mill",
    tagline: "Pure Ground Rice flour, Chilly & Sambar powder",
    distanceKm: 1.7,
    rating: 4.7,
    isOpen: true,
    etaMin: 28,
    address: "51, South Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0018,
    lng: 77.0848,
    imageUrl: storeImg("photo-1615485290382-441e4d049cb5"),
  },
  {
    id: "s_flour3",
    name: "Sri Murugan Batter & Masala Mill",
    category: "flour_mill",
    tagline: "Daily milled Idli batter, Ragi flour & homemade podi",
    distanceKm: 0.8,
    rating: 4.8,
    isOpen: true,
    etaMin: 20,
    address: "12, Bazaar Lane, Pappampatti Pirivu, Coimbatore",
    lat: 11.0026,
    lng: 77.0859,
    imageUrl: storeImg("photo-1586201375761-83865001e31c"),
  },
  {
    id: "s_flour4",
    name: "Ondipudur Heritage Flour & Spice Mill",
    category: "flour_mill",
    tagline: "Traditional stone milled spices, multi-grain flour & fresh batter",
    distanceKm: 6.0,
    rating: 4.9,
    isOpen: true,
    etaMin: 38,
    address: "Bazaar Road, Ondipudur Hub, Coimbatore",
    lat: 10.9918,
    lng: 77.0535,
    imageUrl: storeImg("photo-1615485290382-441e4d049cb5"),
  },

  // ── 4. Meat, Fish & Chicken ───────────────────────────────────────────────
  {
    id: "s_paap4",
    name: "Kongu Country Mutton & Farm Chicken Stall",
    category: "meat_fish",
    tagline: "Fresh tender Mutton, Nattu Kozhi (Country Chicken) & farm eggs",
    distanceKm: 0.6,
    rating: 4.8,
    isOpen: true,
    etaMin: 20,
    address: "Kamaraj Nagar, Pappampatti Pirivu, Coimbatore",
    lat: 11.0041,
    lng: 77.0849,
    imageUrl: storeImg("photo-1607623814075-e51df1bdc82f"),
  },
  {
    id: "s_meat1",
    name: "Annachi Mutton & Farm Chicken Stall",
    category: "meat_fish",
    tagline: "Tender Mutton, Country Chicken & Farm Eggs",
    distanceKm: 0.9,
    rating: 4.8,
    isOpen: true,
    etaMin: 22,
    address: "42, Market Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0045,
    lng: 77.0852,
    imageUrl: storeImg("photo-1607623814075-e51df1bdc82f"),
  },
  {
    id: "s_fish1",
    name: "Kadalkani Fresh Fish & Seafood Stall",
    category: "meat_fish",
    tagline: "Daily fresh Vanjaram slices, Mathi, Nethili & Prawns",
    distanceKm: 1.5,
    rating: 4.8,
    isOpen: true,
    etaMin: 24,
    address: "Daily Market Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0048,
    lng: 77.0839,
    imageUrl: storeImg("photo-1534422298391-e4f8c172dddb"),
  },
  {
    id: "s_meat2",
    name: "Ondipudur Fresh Sea Fish & Mutton Stall",
    category: "meat_fish",
    tagline: "Freshly caught sea fish, crab, prawns & soft mutton curry cuts",
    distanceKm: 6.4,
    rating: 4.9,
    isOpen: true,
    etaMin: 40,
    address: "Market Corner, Ondipudur Hub, Coimbatore",
    lat: 10.9912,
    lng: 77.0515,
    imageUrl: storeImg("photo-1534422298391-e4f8c172dddb"),
  },

  // ── 5. Pharmacy ───────────────────────────────────────────────────────────
  {
    id: "s_paap5",
    name: "Sri Lakshmi Medicals & Healthcare",
    category: "pharmacy",
    tagline: "24/7 chemist, surgicals, OTC medicines & baby care",
    distanceKm: 0.2,
    rating: 4.7,
    isOpen: true,
    etaMin: 12,
    address: "Pappampatti Pirivu Bus Stop, Trichy Road, Coimbatore",
    lat: 11.0022,
    lng: 77.0878,
    imageUrl: storeImg("photo-1587854692152-cbe660dbde88"),
  },
  {
    id: "s_pharm1",
    name: "Sri Ram Medicals & Chemist",
    category: "pharmacy",
    tagline: "24/7 individual chemist, OTC medicines & surgicals",
    distanceKm: 0.8,
    rating: 4.6,
    isOpen: true,
    etaMin: 20,
    address: "Corner of 5th Cross, Pappampatti Pirivu, Coimbatore",
    lat: 11.0029,
    lng: 77.0871,
    imageUrl: storeImg("photo-1587854692152-cbe660dbde88"),
  },
  {
    id: "s_pharm2",
    name: "Apollo Pharmacy Franchise",
    category: "pharmacy",
    tagline: "Branded medicines, health supplements & digital diagnostics",
    distanceKm: 3.4,
    rating: 4.8,
    isOpen: true,
    etaMin: 25,
    address: "Trichy Main Road, Singanallur Junction, Coimbatore",
    lat: 10.9985,
    lng: 77.0248,
    imageUrl: storeImg("photo-1576602976047-174e57a47881"),
  },
  {
    id: "s_pharm3",
    name: "Care Wellness Chemist & Healthcare",
    category: "pharmacy",
    tagline: "Ayurvedic remedies, orthopedic supports & 24/7 emergency drugs",
    distanceKm: 5.7,
    rating: 4.7,
    isOpen: true,
    etaMin: 36,
    address: "Station Road, Ondipudur Hub, Coimbatore",
    lat: 10.9928,
    lng: 77.0542,
    imageUrl: storeImg("photo-1587854692152-cbe660dbde88"),
  },

  // ── 6. Individual Fashion ─────────────────────────────────────────────────
  {
    id: "s_paap6",
    name: "Pappampatti Readymades & Menswear",
    category: "individual_fashion",
    tagline: "Quality cotton shirts, dhotis, pants & casual wear",
    distanceKm: 0.7,
    rating: 4.6,
    isOpen: true,
    etaMin: 22,
    address: "Near SBI ATM, Pappampatti Pirivu, Coimbatore",
    lat: 11.0031,
    lng: 77.086,
    imageUrl: storeImg("photo-1441986300917-64674bd600d8"),
  },
  {
    id: "s_fash1",
    name: "Kumaran Readymades & Menswear",
    category: "individual_fashion",
    tagline: "Individual shop for cotton shirts, pants, dhotis & tailoring",
    distanceKm: 1.1,
    rating: 4.5,
    isOpen: true,
    etaMin: 25,
    address: "29, North Car Street, Pappampatti, Coimbatore",
    lat: 11.0012,
    lng: 77.0855,
    imageUrl: storeImg("photo-1441986300917-64674bd600d8"),
  },
  {
    id: "s_fash2",
    name: "Kovai Cotton Dhotis & Menswear",
    category: "individual_fashion",
    tagline: "Pure Ramraj cotton dhotis, linen shirts & ethnic wear",
    distanceKm: 4.3,
    rating: 4.8,
    isOpen: true,
    etaMin: 32,
    address: "Commercial Hub, Singanallur Junction, Coimbatore",
    lat: 10.9975,
    lng: 77.027,
    imageUrl: storeImg("photo-1617137984095-74e4e5e3613f"),
  },
  {
    id: "s_fash3",
    name: "Nila Kids & Family Readymades",
    category: "individual_fashion",
    tagline: "Kids party wear, cotton frock sets & men's formals",
    distanceKm: 5.9,
    rating: 4.7,
    isOpen: true,
    etaMin: 37,
    address: "Main Market, Ondipudur Hub, Coimbatore",
    lat: 10.993,
    lng: 77.051,
    imageUrl: storeImg("photo-1441986300917-64674bd600d8"),
  },

  // ── 7. Boutiques ──────────────────────────────────────────────────────────
  {
    id: "s_bout1",
    name: "Ananya Designer Boutique",
    category: "boutiques",
    tagline: "Handloom Silk Sarees, Designer Kurtis & Bridal Tailoring",
    distanceKm: 1.2,
    rating: 4.9,
    isOpen: true,
    etaMin: 25,
    address: "18, Heritage Avenue, Trichy Road, Coimbatore",
    lat: 11.0051,
    lng: 77.0882,
    imageUrl: storeImg("photo-1558769132-cb1aea458c5e"),
  },
  {
    id: "s_bout2",
    name: "Vogue Handloom Silk Boutique",
    category: "boutiques",
    tagline: "Kanchipuram Silk Sarees, Designer Blouses & Embroidery",
    distanceKm: 0.9,
    rating: 4.8,
    isOpen: true,
    etaMin: 24,
    address: "77, Heritage Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0036,
    lng: 77.0879,
    imageUrl: storeImg("photo-1583391733956-6c78276477e2"),
  },
  {
    id: "s_bout3",
    name: "Sri Lakshmi Bridal & Embroidery Studio",
    category: "boutiques",
    tagline: "Custom Aari work blouses, bridal lehengas & silk saree stitching",
    distanceKm: 4.1,
    rating: 4.7,
    isOpen: true,
    etaMin: 30,
    address: "Near Temple Arch, Singanallur Junction, Coimbatore",
    lat: 10.9968,
    lng: 77.0258,
    imageUrl: storeImg("photo-1537633552985-df8429e8048b"),
  },
  {
    id: "s_bout4",
    name: "Silk & Threads Custom Boutique",
    category: "boutiques",
    tagline: "Handmade designer kurtis, ethnic dupattas & party gowns",
    distanceKm: 5.8,
    rating: 4.8,
    isOpen: true,
    etaMin: 36,
    address: "Park View, Ondipudur Hub, Coimbatore",
    lat: 10.9922,
    lng: 77.0538,
    imageUrl: storeImg("photo-1558769132-cb1aea458c5e"),
  },

  // ── 8. Showrooms ──────────────────────────────────────────────────────────
  {
    id: "s_show1",
    name: "Sri Saravana Textiles & Electronics Showroom",
    category: "showrooms",
    tagline: "Multistory showroom for silk, smart TVs & appliances",
    distanceKm: 1.4,
    rating: 4.7,
    isOpen: true,
    etaMin: 28,
    address: "100 Feet Commercial Road, Singanallur - Pappampatti stretch, Coimbatore",
    lat: 11.0062,
    lng: 77.0835,
    imageUrl: storeImg("photo-1555529669-e69e7aa0ba9a"),
  },
  {
    id: "s_show2",
    name: "Premier Electronics & Appliances Showroom",
    category: "showrooms",
    tagline: "LG, Samsung 4K TVs, double door fridges & washing machines",
    distanceKm: 3.8,
    rating: 4.8,
    isOpen: true,
    etaMin: 32,
    address: "Trichy Main Road, Singanallur Junction, Coimbatore",
    lat: 10.9988,
    lng: 77.0242,
    imageUrl: storeImg("photo-1593784991095-a205069470b6"),
  },
  {
    id: "s_show3",
    name: "Royal Silk & Diamond Showroom",
    category: "showrooms",
    tagline: "3-Floor wedding silk sarees, gold jewellery & diamond showroom",
    distanceKm: 6.2,
    rating: 4.9,
    isOpen: true,
    etaMin: 40,
    address: "Grand Highway, Ondipudur Hub, Coimbatore",
    lat: 10.9915,
    lng: 77.0522,
    imageUrl: storeImg("photo-1610030469983-98e550d6193c"),
  },

  // ── 9. Fast Fashion ───────────────────────────────────────────────────────
  {
    id: "s_fast1",
    name: "Trendz & Zudio Fast Fashion Outlet",
    category: "fast_fashion",
    tagline: "Branded youth apparel, casuals, denims & footwear",
    distanceKm: 1.6,
    rating: 4.6,
    isOpen: true,
    etaMin: 30,
    address: "Plaza Complex, Ondipudur-Pappampatti Road, Coimbatore",
    lat: 11.0021,
    lng: 77.0891,
    imageUrl: storeImg("photo-1489987707025-afc232f7ea0f"),
  },
  {
    id: "s_fast2",
    name: "Urban Style Youth Apparel",
    category: "fast_fashion",
    tagline: "Graphic tees, cargo trousers, hoodies & casual western tops",
    distanceKm: 3.5,
    rating: 4.7,
    isOpen: true,
    etaMin: 28,
    address: "Express Mall Road, Singanallur Junction, Coimbatore",
    lat: 10.9972,
    lng: 77.0265,
    imageUrl: storeImg("photo-1541099649105-f69ad21f3246"),
  },
  {
    id: "s_fast3",
    name: "Maxx Fashion Store",
    category: "fast_fashion",
    tagline: "Trendy women western wear, denim jackets & kids casuals",
    distanceKm: 6.5,
    rating: 4.8,
    isOpen: true,
    etaMin: 42,
    address: "Shopping Arcade, Ondipudur Hub, Coimbatore",
    lat: 10.9908,
    lng: 77.0545,
    imageUrl: storeImg("photo-1489987707025-afc232f7ea0f"),
  },

  // ── 10. Kitchen Appliances ────────────────────────────────────────────────
  {
    id: "s_kitch1",
    name: "Murugan Stainless Steel & Pressure Cooker House",
    category: "kitchen_appliances",
    tagline: "Stainless steel utensils, mixer grinders & pressure cookers",
    distanceKm: 1.3,
    rating: 4.7,
    isOpen: true,
    etaMin: 26,
    address: "63, Vessels Bazaar Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0032,
    lng: 77.0841,
    imageUrl: storeImg("photo-1556911220-e15b29be8c8f"),
  },
  {
    id: "s_kitch2",
    name: "Sri Ganesh Kitchen Mixer & Vessels World",
    category: "kitchen_appliances",
    tagline: "Preethi grinders, Hawkins cookers & non-stick cookware",
    distanceKm: 3.9,
    rating: 4.8,
    isOpen: true,
    etaMin: 32,
    address: "Bus Stand Road, Singanallur Junction, Coimbatore",
    lat: 10.9981,
    lng: 77.0238,
    imageUrl: storeImg("photo-1584990347449-716c15a3a17a"),
  },
  {
    id: "s_kitch3",
    name: "Kovai Chef Utensils & Stove Clinic",
    category: "kitchen_appliances",
    tagline: "Gas stoves, chimney hoods, cast iron kadai & brassware",
    distanceKm: 6.7,
    rating: 4.6,
    isOpen: true,
    etaMin: 45,
    address: "Bazaar Street, Ondipudur Hub, Coimbatore",
    lat: 10.9902,
    lng: 77.0518,
    imageUrl: storeImg("photo-1556911220-e15b29be8c8f"),
  },

  // ── 11. Home Decor ────────────────────────────────────────────────────────
  {
    id: "s_decor1",
    name: "Vasantham Interior Home Decor Studio",
    category: "home_decor",
    tagline: "Wallpapers, curtains, brass Agal lamps & wall art",
    distanceKm: 1.8,
    rating: 4.8,
    isOpen: true,
    etaMin: 32,
    address: "7, Lakeview Boulevard, Pappampatti, Coimbatore",
    lat: 11.0071,
    lng: 77.0898,
    imageUrl: storeImg("photo-1513519245088-0e12902e5a38"),
  },
  {
    id: "s_decor2",
    name: "Royal Brass Agal & Lamps Emporium",
    category: "home_decor",
    tagline: "Brass Kuthu Vilakku, Agal deepam, divine idols & wall hangings",
    distanceKm: 4.0,
    rating: 4.9,
    isOpen: true,
    etaMin: 34,
    address: "Temple Square, Singanallur Junction, Coimbatore",
    lat: 10.9965,
    lng: 77.0252,
    imageUrl: storeImg("photo-1513519245088-0e12902e5a38"),
  },
  {
    id: "s_decor3",
    name: "Kovai Furnishings & Curtain House",
    category: "home_decor",
    tagline: "Custom velvet drapes, sofa cushions & jute floor rugs",
    distanceKm: 6.1,
    rating: 4.7,
    isOpen: true,
    etaMin: 40,
    address: "Greenway Road, Ondipudur Hub, Coimbatore",
    lat: 10.9919,
    lng: 77.053,
    imageUrl: storeImg("photo-1584100936595-c0654b55a2e2"),
  },

  // ── 12. Fashion Accessories & Gifts ───────────────────────────────────────
  {
    id: "s_acc1",
    name: "Meenakshi Fashion Jewellery & Gift Corner",
    category: "fashion_accessories",
    tagline: "Gold-plated chains, Kammal/Earrings, Thodu, Bangles & Gifts",
    distanceKm: 1.0,
    rating: 4.9,
    isOpen: true,
    etaMin: 24,
    address: "5, Commercial Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0015,
    lng: 77.0868,
    imageUrl: storeImg("photo-1535632066927-ab7c9ab60908"),
  },
  {
    id: "s_acc2",
    name: "Golden Touch Chain & Kammal Gallery",
    category: "fashion_accessories",
    tagline: "Traditional Kammal, Thodu, Antique Chains & Bridal Sets",
    distanceKm: 0.6,
    rating: 4.9,
    isOpen: true,
    etaMin: 19,
    address: "3, Temple Car Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0024,
    lng: 77.0863,
    imageUrl: storeImg("photo-1535632066927-ab7c9ab60908"),
  },
  {
    id: "s_acc3",
    name: "Sparkle Gift Shop & Accessories",
    category: "fashion_accessories",
    tagline: "Customized photo frames, birthday gifts & trendy hair clips",
    distanceKm: 4.2,
    rating: 4.7,
    isOpen: true,
    etaMin: 32,
    address: "High Street, Singanallur Junction, Coimbatore",
    lat: 10.997,
    lng: 77.026,
    imageUrl: storeImg("photo-1549465220-1a8b9238cd48"),
  },
  {
    id: "s_acc4",
    name: "Princess Jhumka & Bangle Palace",
    category: "fashion_accessories",
    tagline: "Kundu jhumka, velvet bangles, bridal thodu & anklet sets",
    distanceKm: 5.6,
    rating: 4.8,
    isOpen: true,
    etaMin: 35,
    address: "Opp. City Bank, Ondipudur Hub, Coimbatore",
    lat: 10.9926,
    lng: 77.0525,
    imageUrl: storeImg("photo-1630019852942-f89202989a59"),
  },

  // ── 13. Bakery ────────────────────────────────────────────────────────────
  {
    id: "s_bakery1",
    name: "Coastline Wood-fired Bakes",
    category: "bakery",
    tagline: "Oven fresh bread, puffs, rusks & buns",
    distanceKm: 1.1,
    rating: 4.9,
    isOpen: true,
    etaMin: 25,
    address: "Main Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0016,
    lng: 77.0873,
    imageUrl: storeImg("photo-1509440159596-0249088772ff"),
  },
  {
    id: "s_bakery2",
    name: "Kovai Hot Oven Bakery & Puffs",
    category: "bakery",
    tagline: "Freshly baked butter croissants, chicken puffs & plum cake",
    distanceKm: 3.7,
    rating: 4.8,
    isOpen: true,
    etaMin: 28,
    address: "Station Road, Singanallur Junction, Coimbatore",
    lat: 10.9984,
    lng: 77.0245,
    imageUrl: storeImg("photo-1555507036-ab1f4038808a"),
  },
  {
    id: "s_bakery3",
    name: "Royal Cake Palace & Sweets",
    category: "bakery",
    tagline: "Custom birthday cakes, chocolate truffles, rusks & cookies",
    distanceKm: 6.3,
    rating: 4.7,
    isOpen: true,
    etaMin: 40,
    address: "Trichy Road, Ondipudur Hub, Coimbatore",
    lat: 10.991,
    lng: 77.0532,
    imageUrl: storeImg("photo-1509440159596-0249088772ff"),
  },

  // ── 14. Book Stalls & Stationery ──────────────────────────────────────────
  {
    id: "s_book1",
    name: "Mega Literature Book House",
    category: "stationery",
    tagline: "Wide range of books, magazines, best sellers & academic books.",
    distanceKm: 0.3,
    rating: 4.6,
    isOpen: true,
    etaMin: 18,
    address: "Market Street 12, Pappampatti Pirivu, Coimbatore",
    lat: 11.0033,
    lng: 77.0861,
    imageUrl: storeImg("photo-1512820790803-83ca734da794"),
  },
  {
    id: "s_book2",
    name: "Paper World Stationery",
    category: "stationery",
    tagline: "Notebooks, pens, art supplies, office & school stationery.",
    distanceKm: 0.5,
    rating: 4.4,
    isOpen: true,
    etaMin: 20,
    address: "24, College Road, Pappampatti Pirivu, Coimbatore",
    lat: 11.0039,
    lng: 77.0867,
    imageUrl: storeImg("photo-1583485088034-697b5bc36b92"),
  },
  {
    id: "s_book3",
    name: "Student Corner Books",
    category: "stationery",
    tagline: "Textbooks, reference books & competitive exam materials.",
    distanceKm: 0.7,
    rating: 4.3,
    isOpen: true,
    etaMin: 22,
    address: "8, School Street, Pappampatti Pirivu, Coimbatore",
    lat: 11.0042,
    lng: 77.0874,
    imageUrl: storeImg("photo-1497633762265-9d179a990aa6"),
  },
  {
    id: "s_book4",
    name: "Creative Cards & Gifts",
    category: "stationery",
    tagline: "Greeting cards, gift items, wrapping materials & more.",
    distanceKm: 1.1,
    rating: 4.7,
    isOpen: true,
    etaMin: 25,
    address: "15, Fancy Bazaar, Pappampatti Pirivu, Coimbatore",
    lat: 11.005,
    lng: 77.088,
    imageUrl: storeImg("photo-1513519245088-0e12902e5a38"),
  },
];

// Curated LocalShoree starter catalog: original neighborhood shops beyond groceries,
// each with products generated from its category below.
export const stores: Store[] = [
  {
    id: "s_threadline_studio",
    name: "Threadline Studio",
    category: "boutiques",
    tagline: "Handpicked fabrics, contemporary styles and thoughtful tailoring",
    distanceKm: 0.8,
    rating: 4.9,
    isOpen: true,
    etaMin: 20,
    address: "18 Market Street, Pappampatti, Coimbatore",
    lat: 11.0031,
    lng: 77.0862,
    imageUrl: storeImg("photo-1558769132-cb1aea458c5e"),
  },
  {
    id: "s_pixel_plug",
    name: "Pixel & Plug Showroom",
    category: "showrooms",
    tagline: "Smart screens, everyday electronics and reliable home upgrades",
    distanceKm: 1.1,
    rating: 4.8,
    isOpen: true,
    etaMin: 25,
    address: "5 Garden Avenue, Pappampatti, Coimbatore",
    lat: 11.0047,
    lng: 77.0871,
    imageUrl: storeImg("photo-1555529669-e69e7aa0ba9a"),
  },
  {
    id: "s_hearth_home",
    name: "Hearth & Home Kitchen",
    category: "kitchen_appliances",
    tagline: "Useful cookware and trusted appliances for modern home kitchens",
    distanceKm: 1.6,
    rating: 4.9,
    isOpen: true,
    etaMin: 30,
    address: "42 Temple Road, Singanallur, Coimbatore",
    lat: 11.0018,
    lng: 77.0258,
    imageUrl: storeImg("photo-1556911220-e15b29be8c8f"),
  },
  {
    id: "s_kadalora_jewellery",
    name: "Kadalora Jewellery & Gifts",
    category: "fashion_accessories",
    tagline: "Everyday jewellery, festive accessories and gifts with local character",
    distanceKm: 1.9,
    rating: 4.7,
    isOpen: true,
    etaMin: 25,
    address: "9 Station Road, Ondipudur, Coimbatore",
    lat: 10.9938,
    lng: 77.0523,
    imageUrl: storeImg("photo-1535632066927-ab7c9ab60908"),
  },
];

const seedProducts = (storeId: string, cat: StoreCategory): Product[] => {
  const catalogs: Record<StoreCategory, Array<Omit<Product, "id" | "storeId">>> = {
    flour_mill: [
      {
        name: "Fresh Idli & Dosa Batter (மாவு)",
        unit: "1 kg",
        price: 45,
        category: "Fresh Batter",
        imageUrl: img("photo-1586201375761-83865001e31c"),
      },
      {
        name: "Freshly Milled Wheat Atta (சம்பா கோதுமை மாவு)",
        unit: "1 kg",
        price: 58,
        category: "Flour",
        imageUrl: img("photo-1509440159596-0249088772ff"),
      },
      {
        name: "Pure Ragi Flour (கேழ்வரகு மாவு)",
        unit: "500 g",
        price: 35,
        category: "Flour",
        imageUrl: img("photo-1615485290382-441e4d049cb5"),
      },
      {
        name: "Freshly Ground Turmeric Powder (மஞ்சள் தூள்)",
        unit: "200 g",
        price: 60,
        category: "Individual Masalas",
        imageUrl: img("photo-1615485290382-441e4d049cb5"),
      },
      {
        name: "Home Made Sambar Powder (சாம்பார் பொடி)",
        unit: "250 g",
        price: 85,
        category: "Individual Masalas",
        imageUrl: img("photo-1596040033229-a9821ebd058d"),
      },
      {
        name: "Pure Red Chilli Powder (தனி மிளகாய் தூள்)",
        unit: "250 g",
        price: 75,
        category: "Individual Masalas",
        imageUrl: img("photo-1596040033229-a9821ebd058d"),
      },
      {
        name: "Fresh Coriander Powder (மல்லி தூள்)",
        unit: "250 g",
        price: 65,
        category: "Individual Masalas",
        imageUrl: img("photo-1596040033229-a9821ebd058d"),
      },
      {
        name: "Authentic Idli Milagai Podi (இட்லி பொடி)",
        unit: "200 g",
        price: 70,
        category: "Individual Masalas",
        imageUrl: img("photo-1596040033229-a9821ebd058d"),
      },
    ],
    palamuthir: [
      {
        name: "Farm Fresh Alphonso Mangoes",
        unit: "1 kg",
        price: 180,
        category: "Fruits",
        imageUrl: img("photo-1553279768-865429fa0078"),
      },
      {
        name: "Fresh Red Pomegranate (மாதுளை)",
        unit: "1 kg",
        price: 190,
        category: "Fruits",
        imageUrl: img("photo-1610832958506-aa56368176cf"),
      },
      {
        name: "Sweet Tender Coconut (இளநீர்)",
        unit: "1 pc",
        price: 50,
        category: "Fresh Drinks",
        imageUrl: img("photo-1525385133512-2f3bdd039054"),
      },
      {
        name: "Fresh Country Tomatoes (தக்காளி)",
        unit: "1 kg",
        price: 38,
        category: "Vegetables",
        imageUrl: img("photo-1592924357228-91a4daadcfea"),
      },
      {
        name: "Fresh Green Spinach Bunch (கீரைகள்)",
        unit: "2 bunches",
        price: 30,
        category: "Vegetables",
        imageUrl: img("photo-1576045057995-568f588f82fb"),
      },
    ],
    meat_fish: [
      {
        name: "Tender Mutton Curry Cut (ஆட்டு இறைச்சி)",
        unit: "500 g",
        price: 440,
        category: "Mutton",
        imageUrl: img("photo-1607623814075-e51df1bdc82f"),
      },
      {
        name: "Fresh Country Chicken Skinless (நாட்டுக் கோழி)",
        unit: "1 kg",
        price: 260,
        category: "Chicken",
        imageUrl: img("photo-1587593810167-a84920ea0781"),
      },
      {
        name: "Fresh Seer Fish / Vanjaram Slices (வஞ்சரம் மீன்)",
        unit: "500 g",
        price: 580,
        category: "Fish",
        imageUrl: img("photo-1534422298391-e4f8c172dddb"),
      },
      {
        name: "Tiger Prawns Cleaned (இறால்)",
        unit: "500 g",
        price: 390,
        category: "Seafood",
        imageUrl: img("photo-1565680018434-b513d5e5fd47"),
      },
      {
        name: "Farm Fresh Country Eggs (நாட்டு முட்டை)",
        unit: "6 pcs",
        price: 84,
        category: "Eggs",
        imageUrl: img("photo-1582722872445-44dc5f7e3c8f"),
      },
    ],
    fashion_accessories: [
      {
        name: "Gold-Plated Designer Chain (செயின்)",
        unit: "1 pc",
        price: 380,
        category: "Jewellery",
        imageUrl: img("photo-1535632066927-ab7c9ab60908"),
      },
      {
        name: "Traditional Temple Jhumka Kammal (கம்மல் / தோடு)",
        unit: "1 pair",
        price: 220,
        category: "Earrings",
        imageUrl: img("photo-1630019852942-f89202989a59"),
      },
      {
        name: "Silk Thread Bangle Set (வளையல்கள்)",
        unit: "Set of 12",
        price: 260,
        category: "Bangles",
        imageUrl: img("photo-1611591475777-233cd7579624"),
      },
      {
        name: "Handcrafted Gift Hamper Box",
        unit: "1 set",
        price: 490,
        category: "Gifts",
        imageUrl: img("photo-1549465220-1a8b9238cd48"),
      },
    ],
    boutiques: [
      {
        name: "Kanchipuram Soft Silk Saree",
        unit: "1 pc",
        price: 3450,
        category: "Sarees",
        imageUrl: img("photo-1610030469983-98e550d6193c"),
      },
      {
        name: "Handloom Cotton Kurti & Dupatta Set",
        unit: "1 set",
        price: 1150,
        category: "Kurtis",
        imageUrl: img("photo-1583391733956-6c78276477e2"),
      },
      {
        name: "Custom Embroidery Designer Blouse Stitching",
        unit: "1 pc",
        price: 850,
        category: "Stitching",
        imageUrl: img("photo-1537633552985-df8429e8048b"),
      },
    ],
    showrooms: [
      {
        name: 'Smart 4K Ultra HD LED TV 43"',
        unit: "1 unit",
        price: 22990,
        category: "Electronics",
        imageUrl: img("photo-1593784991095-a205069470b6"),
      },
      {
        name: "Pure Silk Kanchipuram Bridal Wedding Saree",
        unit: "1 pc",
        price: 7800,
        category: "Textiles",
        imageUrl: img("photo-1610030469983-98e550d6193c"),
      },
    ],
    fast_fashion: [
      {
        name: "Pure Cotton Casual Slim Fit Shirt",
        unit: "1 pc",
        price: 699,
        category: "Men",
        imageUrl: img("photo-1489987707025-afc232f7ea0f"),
      },
      {
        name: "High-Rise Stretch Denim Jeans",
        unit: "1 pc",
        price: 999,
        category: "Women",
        imageUrl: img("photo-1541099649105-f69ad21f3246"),
      },
    ],
    individual_fashion: [
      {
        name: "Traditional Pure Cotton Dhoti & Shirt Combo",
        unit: "1 set",
        price: 899,
        category: "Traditional",
        imageUrl: img("photo-1441986300917-64674bd600d8"),
      },
      {
        name: "Casual Checkered Men Cotton Shirt",
        unit: "1 pc",
        price: 599,
        category: "Menswear",
        imageUrl: img("photo-1489987707025-afc232f7ea0f"),
      },
    ],
    kitchen_appliances: [
      {
        name: "Preethi 750W 3-Jar Mixer Grinder",
        unit: "1 unit",
        price: 3290,
        category: "Appliances",
        imageUrl: img("photo-1584990347449-716c15a3a17a"),
      },
      {
        name: "Hawkins 3 Litre Stainless Steel Pressure Cooker",
        unit: "1 unit",
        price: 1450,
        category: "Cookware",
        imageUrl: img("photo-1584990347449-716c15a3a17a"),
      },
    ],
    home_decor: [
      {
        name: "Traditional Handcrafted Brass Agal Lamp (குத்துவிளக்கு)",
        unit: "1 pair",
        price: 650,
        category: "Decor",
        imageUrl: img("photo-1513519245088-0e12902e5a38"),
      },
      {
        name: "Velvet Designer Cushion Covers (Set of 5)",
        unit: "5 pcs",
        price: 399,
        category: "Furnishings",
        imageUrl: img("photo-1584100936595-c0654b55a2e2"),
      },
    ],
    pharmacy: [
      {
        name: "Paracetamol 500mg OTC",
        unit: "10 tabs",
        price: 22,
        category: "OTC Medicines",
        imageUrl: img("photo-1584308666744-24d5c474f2ae"),
      },
      {
        name: "Pulse Oximeter & Digital Monitor",
        unit: "1 pc",
        price: 450,
        category: "Wellness",
        imageUrl: img("photo-1584362917165-526a968579e8"),
      },
    ],
    stationery: [
      {
        name: "Classmate A4 Ruled Notebooks (Pack of 6)",
        unit: "6 pcs",
        price: 240,
        category: "Notebooks",
        imageUrl: img("photo-1531346878377-a5be20888e57"),
      },
      {
        name: "Gel Pens Blue Set",
        unit: "5 pcs",
        price: 60,
        category: "Pens",
        imageUrl: img("photo-1583485088034-697b5bc36b92"),
      },
    ],
    bakery: [
      {
        name: "Roja Special Butter Mysurpa",
        unit: "250 g",
        price: 140,
        category: "Sweets",
        imageUrl: img("photo-1555507036-ab1f4038808a"),
      },
      {
        name: "Roja Oven Fresh Butter Roti",
        unit: "4 pcs",
        price: 40,
        category: "Bakes",
        imageUrl: img("photo-1509440159596-0249088772ff"),
      },
      {
        name: "Fresh Oven Butter Croissant",
        unit: "1 pc",
        price: 65,
        category: "Bakes",
        imageUrl: img("photo-1555507036-ab1f4038808a"),
      },
      {
        name: "Crispy Egg Puff & Chicken Puff",
        unit: "2 pcs",
        price: 70,
        category: "Savouries",
        imageUrl: img("photo-1509440159596-0249088772ff"),
      },
      {
        name: "Whole Wheat Bread Loaf & Toast",
        unit: "400 g",
        price: 45,
        category: "Bakes",
        imageUrl: img("photo-1509440159596-0249088772ff"),
      },
      {
        name: "Chocolate Truffle Cake Slice",
        unit: "1 pc",
        price: 95,
        category: "Cakes",
        imageUrl: img("photo-1555507036-ab1f4038808a"),
      },
    ],
    grocery: [
      {
        name: "Sona Masoori Premium Rice (பொன்னி அரிசி)",
        unit: "5 kg",
        price: 340,
        category: "Staples",
        imageUrl: img("photo-1586201375761-83865001e31c"),
      },
      {
        name: "Cold Pressed Pure Coconut Oil (தேங்காய் எண்ணெய்)",
        unit: "1 Litre",
        price: 240,
        category: "Oils",
        imageUrl: img("photo-1604719312566-8912e9227c6a"),
      },
      {
        name: "Organic Unpolished Toor Dal (துவரம் பருப்பு)",
        unit: "1 kg",
        price: 145,
        category: "Pulses",
        imageUrl: img("photo-1586201375761-83865001e31c"),
      },
      {
        name: "Premium Whole Urad Dal (உளுந்தம் பருப்பு)",
        unit: "1 kg",
        price: 135,
        category: "Pulses",
        imageUrl: img("photo-1586201375761-83865001e31c"),
      },
      {
        name: "Natural Country Jaggery Powder (நாட்டுச் சர்க்கரை)",
        unit: "1 kg",
        price: 90,
        category: "Staples",
        imageUrl: img("photo-1615485290382-441e4d049cb5"),
      },
      {
        name: "Pure Farm Cow Ghee (பசும் நெய்)",
        unit: "500 ml",
        price: 320,
        category: "Dairy & Ghee",
        imageUrl: img("photo-1604719312566-8912e9227c6a"),
      },
    ],
    restaurants: [
      {
        name: "Special South Indian Meals",
        unit: "1 Plate",
        price: 150,
        category: "Meals",
        imageUrl: img("photo-1626777552726-4a6b54c97e46"),
      },
      {
        name: "Chettinad Chicken Biryani",
        unit: "1 Bucket",
        price: 280,
        category: "Biryani",
        imageUrl: img("photo-1563379091339-03b21ab4a4f8"),
      },
    ],
  };
  return (catalogs[cat] || catalogs.palamuthir).map((p, i) => ({
    ...p,
    id: `${storeId}-p${i}`,
    storeId,
  }));
};

export const productsByStore: Record<string, Product[]> = Object.fromEntries(
  stores.map((s) => [s.id, seedProducts(s.id, s.category)]),
);

export const getStore = (id: string) => stores.find((s) => s.id === id);
