// Synced from @localshore/core 0.1.0; edit packages/localshore-core/src in the Shopper repository.
export type OrderStatus =
  | "new"
  | "accepted"
  | "vendor_accepted"
  | "cancelled_by_vendor"
  | "preparing"
  | "packed"
  | "ready_for_pickup"
  | "assigned"
  | "delivery_partner_assigned"
  | "going_to_vendor"
  | "arrived_at_vendor"
  | "going_to_customer"
  | "arrived_at_customer"
  | "rider_assigned"
  | "rider_accepted"
  | "rider_at_shop"
  | "picked_up"
  | "out_for_delivery"
  | "at_customer"
  | "shipped"
  | "delivered"
  | "cancelled"
  | "returned"
  | "assignment_failed"
  | "delivery_failed";
