// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // Opaque keys (sb_publishable_...) are passed via apikey, not Bearer JWTs
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);

    try {
      return await fetch(input, { ...init, headers });
    } catch (err: any) {
      console.warn("[Supabase connection notice]", err?.message || err);
      throw err;
    }
  };
}

function resolveSupabaseUrl(values: Array<string | undefined>): string | undefined {
  for (const rawValue of values) {
    const raw = rawValue?.trim();
    const value = raw?.includes("=")
      ? raw.slice(raw.indexOf("=") + 1).trim().replace(/^['"]|['"]$/g, "")
      : raw?.replace(/^['"]|['"]$/g, "");
    if (!value) continue;

    try {
      const url = new URL(/^[a-z][a-z\d+.-]*:\/\//i.test(value) ? value : `https://${value}`);
      if (
        (url.protocol === "http:" || url.protocol === "https:") &&
        url.hostname.length > 0 &&
        !/["'=]/.test(url.hostname)
      ) {
        return url.toString().replace(/\/$/, "");
      }
    } catch {
      // Ignore malformed deployment values and try the next configured source.
    }
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const runtimeEnv = typeof process !== "undefined" ? process.env : undefined;
  const metaEnv = typeof import.meta !== "undefined" ? import.meta.env : undefined;
  const SUPABASE_PROJECT_ID =
    metaEnv?.["VITE_SUPABASE_PROJECT_ID"] || runtimeEnv?.["SUPABASE_PROJECT_ID"];
  const SUPABASE_URL = resolveSupabaseUrl([
    metaEnv?.["VITE_SUPABASE_URL"],
    runtimeEnv?.["SUPABASE_URL"],
    runtimeEnv?.["VITE_SUPABASE_URL"],
    SUPABASE_PROJECT_ID ? `https://${SUPABASE_PROJECT_ID}.supabase.co` : undefined,
  ]);
  const SUPABASE_PUBLISHABLE_KEY =
    metaEnv?.["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    runtimeEnv?.["SUPABASE_PUBLISHABLE_KEY"] ||
    runtimeEnv?.["VITE_SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop) {
    if (!_supabase) _supabase = createSupabaseClient();
    const value = (_supabase as any)[prop];
    return typeof value === "function" ? value.bind(_supabase) : value;
  },
});
